// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AFDefine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AFMsg {

  /// <summary>Holder for reflection information generated from AFDefine.proto</summary>
  public static partial class AFDefineReflection {

    #region Descriptor
    /// <summary>File descriptor for AFDefine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AFDefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5BRkRlZmluZS5wcm90bxIFQUZNc2cqtgoKDkVHYW1lRXZlbnRDb2RlEhAK",
            "DEVHRUNfU1VDQ0VTUxAAEhUKEUVHRUNfVU5LT1dOX0VSUk9SEAESFgoSRUdF",
            "Q19BQ0NPVU5UX0VYSVNUEAISGwoXRUdFQ19BQ0NPVU5UUFdEX0lOVkFMSUQQ",
            "AxIWChJFR0VDX0FDQ09VTlRfVVNJTkcQBBIXChNFR0VDX0FDQ09VTlRfTE9D",
            "S0VEEAUSGAoURUdFQ19BQ0NPVU5UX1NVQ0NFU1MQBhIbChdFR0VDX1ZFUklG",
            "WV9LRVlfU1VDQ0VTUxAHEhgKFEVHRUNfVkVSSUZZX0tFWV9GQUlMEAgSHQoZ",
            "RUdFQ19TRUxFQ1RTRVJWRVJfU1VDQ0VTUxAJEhoKFkVHRUNfU0VMRUNUU0VS",
            "VkVSX0ZBSUwQChIYChRFR0VDX0NIQVJBQ1RFUl9FWElTVBBuEhoKFkVHRUNf",
            "U1ZSWk9ORUlEX0lOVkFMSUQQbxIZChVFR0VDX0NIQVJBQ1RFUl9OVU1PVVQQ",
            "cBIaChZFR0VDX0NIQVJBQ1RFUl9JTlZBTElEEHESGwoXRUdFQ19DSEFSQUNU",
            "RVJfTk9URVhJU1QQchIYChRFR0VDX0NIQVJBQ1RFUl9VU0lORxBzEhkKFUVH",
            "RUNfQ0hBUkFDVEVSX0xPQ0tFRBB0EhYKEkVHRUNfWk9ORV9PVkVSTE9BRBB1",
            "EhMKD0VHRUNfTk9UX09OTElORRB2EhcKE0VHRUNfQUxSRUFZX0lOX1RFQU0Q",
            "dxIcChhFR0VDX0lOVkFMSURfVEVBTV9JTlZJVEUQeBISCg5FR0VDX1RFQU1f",
            "RlVMTBB5EhoKFkVHRUNfTUFJTF9VUERBVEVfRVJST1IQehIcChhFR0VDX01B",
            "SUxfVE9OQU1FX0lOVkFMSUQQexIaChZFR0VDX01BSUxfREVMRVRFX0VSUk9S",
            "EHwSGwoXRUdFQ19NQUlMX1RPV05BTUVfRVFVQUwQfRITCg9FR0VDX0xBQ0tf",
            "TU9ORVkQfhIVChFFR0VDX0ZVTExfUEFDS0FHRRB/EhYKEUVHRUNfSU5WQUxJ",
            "RF9JVEVNEIABEh0KGEVHRUNfSU5WQUxJRF9DT05TSUdOTUVOVBCBARIYChNF",
            "R0VDX05PVF9FTk9VR0hfVklQEIIBEhQKD0VHRUNfTkVFRF9MRVZFTBCDARIZ",
            "ChRFR0VDX01BWF9GUklFTkRfTElTVBCEARIYChNFR0VDX01BWF9FTkVNWV9M",
            "SVNUEIUBEhgKE0VHRUNfTUFYX0dBTkdTX0xTSVQQhgESGgoVRUdFQ19MSU1J",
            "VFNfVE9fUklHSFRTEIcBEhwKF0VHRUNfSU5WQUxJRF9HQU5HU19OQU1FEIgB",
            "EhwKF0VHRUNfUkVQRUFUX0VOVEVSX0dBTkdTEIkBEh0KGEVHRUNfSU5WQUxJ",
            "RF9HQU5HU01FTUJFUhCKARIcChdFR0VDX01BU1RFUl9MRUFWRV9HQU5HUxCL",
            "ARIbChZFR0VDX0dBTkdTX1RJVExFX09VVE9GEIwBEh0KGEVHRUNfRU5URVJf",
            "R0FURVdBWV9GQUlMRBCNARIYChNFR0VDX05PX1NFUlZFUjRaT05FEI4BEhcK",
            "EkVHRUNfSU5WQUxJRF9TS0lMTBCPARIcChdFR0VDX0VOVEVSX0dBTUVfU1VD",
            "Q0VTUxCQARIeChlFR0VDX0NSRUFURV9HVUlMRF9TVUNDRVNTEMgBEhwKF0VH",
            "RUNfSk9JTl9HVUlMRF9TVUNDRVNTEMkBEh0KGEVHRUNfTEVBVkVfR1VJTERf",
            "U1VDQ0VTUxDKASrgLAoKRUdhbWVNc2dJRBIPCgtFR01JX1VOS05PVxAAEhUK",
            "EUVHTUlfRVZFTlRfUkVTVUxUEAESGAoURUdNSV9FVkVOVF9UUkFOU1BPTkQQ",
            "AhIVChFFR01JX0NMT1NFX1NPQ0tFVBADEh0KGUVHTUlfTVRMX1dPUkxEX1JF",
            "R0lTVEVSRUQQChIfChtFR01JX01UTF9XT1JMRF9VTlJFR0lTVEVSRUQQCxIa",
            "ChZFR01JX01UTF9XT1JMRF9SRUZSRVNIEAwSHQoZRUdNSV9MVE1fTE9HSU5f",
            "UkVHSVNURVJFRBAUEh8KG0VHTUlfTFRNX0xPR0lOX1VOUkVHSVNURVJFRBAV",
            "EhoKFkVHTUlfTFRNX0xPR0lOX1JFRlJFU0gQFhIeChpFR01JX1BUV0dfUFJP",
            "WFlfUkVHSVNURVJFRBAeEiAKHEVHTUlfUFRXR19QUk9YWV9VTlJFR0lTVEVS",
            "RUQQHxIbChdFR01JX1BUV0dfUFJPWFlfUkVGUkVTSBAgEhwKGEVHTUlfR1RX",
            "X0dBTUVfUkVHSVNURVJFRBAoEh4KGkVHTUlfR1RXX0dBTUVfVU5SRUdJU1RF",
            "UkVEECkSGQoVRUdNSV9HVFdfR0FNRV9SRUZSRVNIECoSFwoTRUdNSV9HVEdf",
            "QlJPQ0FTVE1TRxArEhUKEUVHTUlfU1RTX05FVF9JTkZPEDISFwoTRUdNSV9T",
            "VFNfSEVBUlRfQkVBVBBkEhIKDkVHTUlfUkVRX0xPR0lOEGUSEgoORUdNSV9B",
            "Q0tfTE9HSU4QZhITCg9FR01JX1JFUV9MT0dPVVQQZxIXChNFR01JX1JFUV9X",
            "T1JMRF9MSVNUEG4SFwoTRUdNSV9BQ0tfV09STERfTElTVBBvEhoKFkVHTUlf",
            "UkVRX0NPTk5FQ1RfV09STEQQcBIaChZFR01JX0FDS19DT05ORUNUX1dPUkxE",
            "EHESIAocRUdNSV9SRVFfS0lDS19DTElFTlRfSU5XT1JMRBByEhgKFEVHTUlf",
            "UkVRX0NPTk5FQ1RfS0VZEHgSGAoURUdNSV9BQ0tfQ09OTkVDVF9LRVkQehIb",
            "ChZFR01JX1JFUV9TRUxFQ1RfU0VSVkVSEIIBEhsKFkVHTUlfQUNLX1NFTEVD",
            "VF9TRVJWRVIQgwESFwoSRUdNSV9SRVFfUk9MRV9MSVNUEIQBEhcKEkVHTUlf",
            "QUNLX1JPTEVfTElTVBCFARIZChRFR01JX1JFUV9DUkVBVEVfUk9MRRCGARIZ",
            "ChRFR01JX1JFUV9ERUxFVEVfUk9MRRCHARIaChVFR01JX1JFUV9SRUNPVkVS",
            "X1JPTEUQiAESGAoTRUdNSV9SRVFfRU5URVJfR0FNRRCWARIYChNFR01JX0FD",
            "S19FTlRFUl9HQU1FEJcBEhgKE0VHTUlfUkVRX0xFQVZFX0dBTUUQmAESGAoT",
            "RUdNSV9BQ0tfTEVBVkVfR0FNRRCZARIXChJFR01JX1JFUV9TV0FQX0dBTUUQ",
            "mgESGAoTRUdNSV9SRVFfU1dBUF9TQ0VORRCbARIYChNFR01JX0FDS19TV0FQ",
            "X1NDRU5FEJwBEhgKE0VHTUlfUkVRX0VORF9CQVRUTEUQnQESGAoTRUdNSV9B",
            "Q0tfRU5EX0JBVFRMRRCeARIaChVFR01JX0FDS19FTlRJVFlfRU5URVIQyAES",
            "GgoVRUdNSV9BQ0tfRU5USVRZX0xFQVZFEMkBEiQKH0VHTUlfQUNLX0VOVElU",
            "WV9EQVRBX05PREVfRU5URVIQygESJQogRUdNSV9BQ0tfRU5USVRZX0RBVEFf",
            "VEFCTEVfRU5URVIQywESFwoSRUdNSV9BQ0tfTk9ERV9EQVRBENIBEhUKEEVH",
            "TUlfQUNLX0FERF9ST1cQ3AESGAoTRUdNSV9BQ0tfUkVNT1ZFX1JPVxDdARIW",
            "ChFFR01JX0FDS19TV0FQX1JPVxDeARIYChNFR01JX0FDS19UQUJMRV9EQVRB",
            "EN8BEhkKFEVHTUlfQUNLX1RBQkxFX0NMRUFSEOUBEhgKE0VHTUlfQUNLX1RB",
            "QkxFX1NPUlQQ5gESEgoNRUdNSV9SRVFfTU9WRRDrARISCg1FR01JX0FDS19N",
            "T1ZFEOwBEhkKFEVHTUlfUkVRX01PVkVfSU1NVU5FEO0BEhkKFEVHTUlfQUNL",
            "X01PVkVfSU1NVU5FEO4BEhsKFkVHTUlfUkVRX1NLSUxMX09CSkVDVFgQ8AES",
            "GwoWRUdNSV9BQ0tfU0tJTExfT0JKRUNUWBDxARIXChJFR01JX1JFUV9TS0lM",
            "TF9QT1MQ8gESFwoSRUdNSV9BQ0tfU0tJTExfUE9TEPMBEhkKFEVHTUlfUkVR",
            "X0lURU1fT0JKRUNUEPQBEhkKFEVHTUlfQUNLX0lURU1fT0JKRUNUEPUBEhYK",
            "EUVHTUlfUkVRX0lURU1fUE9TEPYBEhYKEUVHTUlfQUNLX0lURU1fUE9TEPcB",
            "EhIKDUVHTUlfUkVRX0NIQVQQ+gESEgoNRUdNSV9BQ0tfQ0hBVBD7ARIXChJF",
            "R01JX1JFUV9TQUxFX0lURU0Q/AESGAoTRUdNSV9SRVFfU1BMSVRfSVRFTRD9",
            "ARIaChVFR01JX1JFUV9QUk9EVUNFX0lURU0Q/gESFwoSRUdNSV9SRVFfUElD",
            "S19JVEVNEP8BEhkKFEVHTUlfUkVRX0FDQ0VQVF9UQVNLEIACEhwKF0VHTUlf",
            "UkVRX0NPTVBFTEVURV9UQVNLEIECEhYKEUVHTUlfUkVRX0pPSU5fUFZQEIQC",
            "EhYKEUVHTUlfUkVRX0VYSVRfUFZQEIUCEhcKEkVHTVRfQUNLX1NUQVJUX1BW",
            "UBCGAhIcChdFR01JX1JFUV9TRUFSQ0hfT1BQTkVOVBCYAhIcChdFR01JX0FD",
            "S19TRUFSQ0hfT1BQTkVOVBCZAhIbChZFR01UX1JFUV9TVEFSVF9PUFBORU5U",
            "EJoCEhsKFkVHTVRfQUNLX1NUQVJUX09QUE5FTlQQmwISGwoWRUdNSV9BQ0tf",
            "T05MSU5FX05PVElGWRCiAhIcChdFR01JX0FDS19PRkZMSU5FX05PVElGWRCj",
            "AhIaChVFR01JX1JFUV9DUkVBVEVfR1VJTEQQrAISGgoVRUdNSV9BQ0tfQ1JF",
            "QVRFX0dVSUxEEK0CEhgKE0VHTUlfUkVRX0pPSU5fR1VJTEQQrgISGAoTRUdN",
            "SV9BQ0tfSk9JTl9HVUlMRBCvAhIZChRFR01JX1JFUV9MRUFWRV9HVUlMRBCw",
            "AhIZChRFR01JX0FDS19MRUFWRV9HVUlMRBCxAhIXChJFR01JX1JFUV9PUFJf",
            "R1VJTEQQsgISFwoSRUdNSV9BQ0tfT1BSX0dVSUxEELMCEhoKFUVHTUlfUkVR",
            "X1NFQVJDSF9HVUlMRBC0AhIaChVFR01JX0FDS19TRUFSQ0hfR1VJTEQQtQIS",
            "GwoWRUdNSV9SRVFfT1BSX0dVSUxESU5GTxC2AhIbChZFR01JX0FDS19PUFJf",
            "R1VJTERJTkZPELcCEh0KGEVHTUlfUkVRX0dVSUxERUNUWVBFSU5GTxC4AhId",
            "ChhFR01JX0FDS19HVUlMREVDVFlQRUlORk8QuQISHQoYRUdNSV9TRVRfR1VJ",
            "TERFQ1RZUEVJTkZPELoCEh0KGEVHTUlfUmVxRW50ZXJHdWlsZEVjdHlwZRC7",
            "AhIeChlFR0VDX1JFUV9DUkVBVEVfQ0hBVEdST1VQEJADEh4KGUVHRUNfQUNL",
            "X0NSRUFURV9DSEFUR1JPVVAQkQMSHAoXRUdFQ19SRVFfSk9JTl9DSEFUR1JP",
            "VVAQkgMSHAoXRUdFQ19BQ0tfSk9JTl9DSEFUR1JPVVAQkwMSHQoYRUdFQ19S",
            "RVFfTEVBVkVfQ0hBVEdST1VQEJQDEh0KGEVHRUNfQUNLX0xFQVZFX0NIQVRH",
            "Uk9VUBCVAxIkCh9FR0VDX1JFUV9TVUJTQ1JJUFRJT05fQ0hBVEdST1VQEJYD",
            "EioKJUVHRUNfUkVRX0NBTkNFTFNVQlNDUklQVElPTl9DSEFUR1JPVVAQlwMS",
            "HgoZRUdFQ19SRVFfSU5WSVRFX0NIQVRHUk9VUBCYAxIeChlFR0VDX0FDS19J",
            "TlZJVEVfQ0hBVEdST1VQEJkDEhwKF0VHRUNfUkVRX0tJQ0tfQ0hBVEdST1VQ",
            "EJoDEhwKF0VHRUNfQUNLX0tJQ0tfQ0hBVEdST1VQEJsDEh8KGkVHRUNfUkVR",
            "X0NIQVRHUk9VUF9UT19URUFNEMIDEh8KGkVHRUNfQUNLX0NIQVRHUk9VUF9U",
            "T19URUFNEMMDEiUKIEVHRUNfUkVRX0lOVEVOU0lGWUxFVkVMX1RPX0VRVUlQ",
            "EPQDEiUKIEVHRUNfQUNLX0lOVEVOU0lGWUxFVkVMX1RPX0VRVUlQEPUDEhsK",
            "FkVHRUNfUkVRX0hPTEVfVE9fRVFVSVAQ9gMSGwoWRUdFQ19BQ0tfSE9MRV9U",
            "T19FUVVJUBD3AxIhChxFR0VDX1JFUV9JTkxBWVNUT05FX1RPX0VRVUlQEPgD",
            "EiEKHEVHRUNfQUNLX0lOTEFZU1RPTkVfVE9fRVFVSVAQ+QMSIwoeRUdFQ19S",
            "RVFfRUxFTUVOVExFVkVMX1RPX0VRVUlQEPoDEiMKHkVHRUNfQUNLX0VMRU1F",
            "TlRMRVZFTF9UT19FUVVJUBD7AxIcChdFR0VDX1JFUV9TRVRfRklHSFRfSEVS",
            "TxD8AxIUCg9FR0VDX1dFQVJfRVFVSVAQ/QMSFwoSRUdFQ19UQUtFT0ZGX0VR",
            "VUlQEP4DEhoKFUVHRUNfUkVRX01JTklOR19USVRMRRDYBBIXChJFR0VDX1JF",
            "UV9TRU5EX01BSUwQvAUSFwoSRUdFQ19SRVFfRFJBV19NQUlMEL0FEhkKFEVH",
            "RUNfUkVRX0RFTEVURV9NQUlMEL4FEiAKG0VHTUlfQUNLX0NMT05FX09CSkVD",
            "VF9FTlRSWRCgBhIgChtFR01JX0FDS19DTE9ORV9PQkpFQ1RfTEVBVkUQoQYS",
            "KQokRUdNSV9BQ0tfQ0xPTkVfT0JKRUNUX1BST1BFUlRZX0VOVFJZEKIGEicK",
            "IkVHTUlfQUNLX0NMT05FX09CSkVDVF9SRUNPUkRfRU5UUlkQowYSIAobRUdN",
            "SV9BQ0tfQ0xPTkVfUFJPUEVSVFlfSU5UEKoGEiIKHUVHTUlfQUNLX0NMT05F",
            "X1BST1BFUlRZX0ZMT0FUEKsGEiMKHkVHTUlfQUNLX0NMT05FX1BST1BFUlRZ",
            "X1NUUklORxCsBhIjCh5FR01JX0FDS19DTE9ORV9QUk9QRVJUWV9ET1VCTEUQ",
            "rQYSIwoeRUdNSV9BQ0tfQ0xPTkVfUFJPUEVSVFlfT0JKRUNUEK4GEhsKFkVH",
            "TUlfQUNLX0NMT05FX0FERF9ST1cQtAYSHgoZRUdNSV9BQ0tfQ0xPTkVfUkVN",
            "T1ZFX1JPVxC1BhIcChdFR01JX0FDS19DTE9ORV9TV0FQX1JPVxC2BhIeChlF",
            "R01JX0FDS19DTE9ORV9SRUNPUkRfSU5UELcGEiAKG0VHTUlfQUNLX0NMT05F",
            "X1JFQ09SRF9GTE9BVBC4BhIhChxFR01JX0FDS19DTE9ORV9SRUNPUkRfRE9V",
            "QkxFELkGEiEKHEVHTUlfQUNLX0NMT05FX1JFQ09SRF9TVFJJTkcQugYSIQoc",
            "RUdNSV9BQ0tfQ0xPTkVfUkVDT1JEX09CSkVDVBC7BhIgChtFR01JX0FDS19D",
            "TE9ORV9SRUNPUkRfQ0xFQVIQvAYSHwoaRUdNSV9BQ0tfQ0xPTkVfUkVDT1JE",
            "X1NPUlQQvQYSGAoTRUdNSV9SRVFTV0lDSFNFUlZFUhDIBhIYChNFR01JX0FD",
            "S1NXSUNIU0VSVkVSEMkGEhkKFEVHTUlfUkVRX0NSRUFURV9URUFNENwGEhkK",
            "FEVHTUlfQUNLX0NSRUFURV9URUFNEN0GEhcKEkVHTUlfUkVRX0pPSU5fVEVB",
            "TRDeBhIXChJFR01JX0FDS19KT0lOX1RFQU0Q3wYSGAoTRUdNSV9SRVFfTEVB",
            "VkVfVEVBTRDgBhIYChNFR01JX0FDS19MRUFWRV9URUFNEOEGEhkKFEVHTUlf",
            "UkVRX0lOVklURV9URUFNEOIGEhwKF0VHTUlfUkVRX09QUk1FTUJFUl9URUFN",
            "EOMGEhwKF0VHTUlfQUNLX09QUk1FTUJFUl9URUFNEOQGEh8KGkVHTUlfUkVR",
            "X1RFQU1fRU5URVJfRUNUWVBFEOUGEh8KGkVHTUlfQUNLX1RFQU1fRU5URVJf",
            "RUNUWVBFEOYGEhsKFkVHTUlfUkVRX01BUF9HUklEX0lORk8QhAcSGwoWRUdN",
            "SV9BQ0tfTUFQX0dSSURfSU5GTxCFBxIaChVFR01JX1JFUV9CSUdfTUFQX0lO",
            "Rk8QhgcSGgoVRUdNSV9BQ0tfQklHX01BUF9JTkZPEIcHEhsKFkVHTUlfUkVR",
            "X0hPTERfTUFQX0dSSUQQjgcSGwoWRUdNSV9BQ0tfSE9MRF9NQVBfR1JJRBCP",
            "BxIgChtFR01JX1JFUV9MRUFWRV9NU0dfTUFQX0dSSUQQkAcSIAobRUdNSV9B",
            "Q0tfTEVBVkVfTVNHX01BUF9HUklEEJEHEiAKG0VHTUlfUkVRX0dFVF9NQVBf",
            "R1JJRF9BV0FSRBCSBxIgChtFR01JX0FDS19HRVRfTUFQX0dSSURfQVdBUkQQ",
            "kwcSHgoZRUdNSV9SRVFfTUFQX0dSSURfSFVOVElORxCUBxIeChlFR01JX0FD",
            "S19NQVBfR1JJRF9IVU5USU5HEJUHEh8KGkVHTUlfUkVRX01BUF9HUklEX0tJ",
            "TkdfV0FSEJYHEh8KGkVHTUlfQUNLX01BUF9HUklEX0tJTkdfV0FSEJcHEh4K",
            "GUVHTUlfUkVRX0NNRF9QUk9QRVJUWV9JTlQQ6AcSHgoZRUdNSV9SRVFfQ01E",
            "X1BST1BFUlRZX1NUUhDpBxIhChxFR01JX1JFUV9DTURfUFJPUEVSVFlfT0JK",
            "RUNUEOoHEiAKG0VHTUlfUkVRX0NNRF9QUk9QRVJUWV9GTE9BVBDrBxIcChdF",
            "R01JX1JFUV9DTURfUkVDT1JEX0lOVBDsBxIcChdFR01JX1JFUV9DTURfUkVD",
            "T1JEX1NUUhDtBxIfChpFR01JX1JFUV9DTURfUkVDT1JEX09CSkVDVBDuBxIe",
            "ChlFR01JX1JFUV9DTURfUkVDT1JEX0ZMT0FUEO8HEhgKE0VHTUlfUkVRX0NN",
            "RF9OT1JNQUwQ8AcSHAoXRUdNSV9SRVFfUFZQQVBQTFlNQUNUQ0gQzAgSHAoX",
            "RUdNSV9BQ0tfUFZQQVBQTFlNQUNUQ0gQzQgSHQoYRUdNSV9SRVFfQ1JFQVRF",
            "UFZQRUNUWVBFEM4IEh0KGEVHTUlfQUNLX0NSRUFURVBWUEVDVFlQRRDPCBIb",
            "ChZFR01JX1JFUV9CVVlfRk9STV9TSE9QEJBOEhsKFkVHTUlfQUNLX0JVWV9G",
            "T1JNX1NIT1AQkU4SHwoaRUdNSV9SRVFfTU9WRV9CVUlMRF9PQkpFQ1QQkk4S",
            "HwoaRUdNSV9BQ0tfTU9WRV9CVUlMRF9PQkpFQ1QQk04SGgoVRUdNSV9SRVFf",
            "VVBfQlVJTERfTFZMEPVOEhkKFEVHTUlfUkVRX0NSRUFURV9JVEVNEPZOEhsK",
            "FkVHTUlfUkVRX0JVSUxEX09QRVJBVEUQ904qUgoJRUl0ZW1UeXBlEg0KCUVJ",
            "VF9FUVVJUBAAEgsKB0VJVF9HRU0QARIMCghFSVRfSVRFTRACEgwKCEVJVF9D",
            "QVJEEAMSDQoJRUlUX1RPS0VOEAQqkQEKEUVHYW1lRXF1aXBTdWJUeXBlEhQK",
            "EEVRVUlQVFlQRV9XRUFQT04QABIUChBFUVVJUFRZUEVfSEVMTUVUEAESEwoP",
            "RVFVSVBUWVBFX0FSTU9SEAISEwoPRVFVSVBUWVBFX1dSSVNUEAMSEgoORVFV",
            "SVBUWVBFX1BBTlQQBBISCg5FUVVJUFRZUEVfQk9PVBAFKswBCg9FR2FtZUdl",
            "bVN1YlR5cGUSFAoQRUdHU1RZUEVfR0VNX0FUSxAAEhQKEEVHR1NUWVBFX0dF",
            "TV9ERUYQARIYChRFR0dTVFlQRV9HRU1fVEhVTkRFUhACEhUKEUVHR1NUWVBF",
            "X0dFTV9GSVJFEAMSFgoSRUdHU1RZUEVfR0VNX0xJR0hUEAQSFQoRRUdHU1RZ",
            "UEVfR0VNX1dJTkQQBRIUChBFR0dTVFlQRV9HRU1fSUNFEAYSFwoTRUdHU1RZ",
            "UEVfR0VNX1BPSVNPThAHKrMBChBFR2FtZUl0ZW1TdWJUeXBlEhMKD0VHSVRf",
            "SVRFTV9XQVRFUhAAEhUKEUVHSVRfSVRFTV9ESUFNT05EEAESFgoSRUdJVF9J",
            "VEVNX0NVUlJFTkNZEAISEQoNRUdJVF9JVEVNX0VYUBADEhAKDEVHSVRfSVRF",
            "TV9IUBAEEhAKDEVHSVRfSVRFTV9NUBAFEhAKDEVHSVRfSVRFTV9TUBAGEhIK",
            "DkVHSVRfSVRFTV9QQUNLEAcqYQoQRUdhbWVDYXJkU3ViVHlwZRIOCgpFR0NT",
            "VF9OT05FEAASEgoORUdDU1RfU1RSRU5HVEgQARIRCg1FR0NTVF9BR0lMSVRZ",
            "EAISFgoSRUdDU1RfSU5URUxMSUdFTkNFEAMqdwoRRUdhbWVUb2tlblN1YlR5",
            "cGUSFgoSRUdUU1RfVE9LRU5fUkVCT1JOEAASGAoURUdUU1RfVE9LRU5fUE9T",
            "SVRJT04QARIWChJFR1RTVF9UT0tFTl9CT1VOVFkQAhIYChRFR1RTVF9UT0tF",
            "Tl9BQ1RJVklUWRADKmUKFEVHYW1lSXRlbUV4cGlyZWRUeXBlEg4KCkVHSUVU",
            "X05PTkUQABITCg9FR0lFVF9VU0VfVElNRVMQARITCg9FR0lFVF9SRUFMX1RJ",
            "TUUQAhITCg9FR0lFVF9FTkRfSU5ERVgQAypZChJFRHJhd0Ryb3BJdGVtU3Rh",
            "dGUSFQoRRV9EUkFXX1NUQVRFX05PTkUQABIVChFFX0RSQVdfU1RBVEVfR0FJ",
            "ThABEhUKEUVfRFJBV19TVEFURV9SRUNWEAIqcwoPRUd1aWxkUG93ZXJUeXBl",
            "EhsKF0dVSUxEX1BPV0VSX1RZUEVfTk9STUFMEAASIwofR1VJTERfUE9XRVJf",
            "VFlQRV9WSUNFX1BSRVNJREVOVBABEh4KGkdVSUxEX1BPV0VSX1RZUEVfUFJF",
            "U0lERU5UEAIqVgoKRVRhc2tTdGF0ZRITCg9UQVNLX0lOX1BST0NFU1MQABIN",
            "CglUQVNLX0RPTkUQARITCg9UQVNLX0RSQVdfQVdBUkQQAhIPCgtUQVNLX0ZJ",
            "TklTSBADKqkCCglFVGFza1R5cGUSIAocVEFTS19MRVZFTF9VUERBVEVfU09N",
            "RV9MRVZFTBAAEhQKEFRBU0tfUEFTU19FQ1RZUEUQARIaChZUQVNLX1BBU1Nf",
            "RUNUWVBFX0NPVU5UEAISJAogVEFTS19QQVNTX1NPTUVfVFlQRV9FQ1RZUEVf",
            "Q09VTlQQAxIbChdUQVNLX1VQREFURV9TS0lMTF9DT1VOVBAEEhYKElRBU0tf",
            "Q09OU1VNRV9NT05FWRAFEhgKFFRBU0tfQ09OU1VNRV9ESUFNT05EEAYSFAoQ",
            "VEFTS19BUkVOQV9DT1VOVBAHEhsKF1RBU0tfS0lMTF9NT05TVEVSX0NPVU5U",
            "EAgSIAocVEFTS19LSUxMX1NPTUVfTU9OU1RFUl9DT1VOVBAJKjUKC0VCYXR0",
            "bGVUeXBlEhEKDUJBVFRMRV9TSU5HTEUQABITCg9CQVRUTEVfUFZFX1RFQU0Q",
            "ASqQAQoJRVJhbmtUeXBlEhMKD0VSVF9QTEFZRVJfTk9ORRAAEhQKEEVSVF9Q",
            "TEFZRVJfTEVWRUwQARITCg9FUlRfRklHSFRfVkFMVUUQAhIUChBFUlRfUExB",
            "WUVSX01PTkVZEAMSEwoPRVJUX0dVSUxEX0xFVkVMEAQSGAoURVJUX0dVSUxE",
            "X0tJTkdTT1VSQ0UQBSpHCghFTlBDVHlwZRITCg9FTlBDVFlQRV9OT1JNQUwQ",
            "ABIRCg1FTlBDVFlQRV9IRVJPEAESEwoPRU5QQ1RZUEVfVFVSUkVUEAIqVgoN",
            "RVByb3BlcnR5VHlwZRIMCghFUFRfTk9ORRAAEhAKDEVQVF9TVFJFTkdUSBAB",
            "Eg8KC0VQVF9BR0lMSVRZEAISFAoQRVBUX0lOVEVMTElHRU5DRRADKocBChBF",
            "R2FtZUVsZW1lbnRUeXBlEhUKEUVFTEVNRU5UVFlQRV9GSVJFEAASFgoSRUVM",
            "RU1FTlRUWVBFX0xJR0hUEAESFQoRRUVMRU1FTlRUWVBFX1dJTkQQAhIUChBF",
            "RUxFTUVOVFRZUEVfSUNFEAMSFwoTRUVMRU1FTlRUWVBFX1BPSVNPThAEYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::AFMsg.EGameEventCode), typeof(global::AFMsg.EGameMsgID), typeof(global::AFMsg.EItemType), typeof(global::AFMsg.EGameEquipSubType), typeof(global::AFMsg.EGameGemSubType), typeof(global::AFMsg.EGameItemSubType), typeof(global::AFMsg.EGameCardSubType), typeof(global::AFMsg.EGameTokenSubType), typeof(global::AFMsg.EGameItemExpiredType), typeof(global::AFMsg.EDrawDropItemState), typeof(global::AFMsg.EGuildPowerType), typeof(global::AFMsg.ETaskState), typeof(global::AFMsg.ETaskType), typeof(global::AFMsg.EBattleType), typeof(global::AFMsg.ERankType), typeof(global::AFMsg.ENPCType), typeof(global::AFMsg.EPropertyType), typeof(global::AFMsg.EGameElementType), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///所有的网络逻辑事件枚举都在这里 
  /// </summary>
  public enum EGameEventCode {
    /// <summary>
    /// 操作成功
    /// </summary>
    [pbr::OriginalName("EGEC_SUCCESS")] EgecSuccess = 0,
    /// <summary>
    /// 未知错误
    /// </summary>
    [pbr::OriginalName("EGEC_UNKOWN_ERROR")] EgecUnkownError = 1,
    /// <summary>
    /// 注册时账号在数据库中已存在
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_EXIST")] EgecAccountExist = 2,
    /// <summary>
    /// 账号不存在或者密码错误
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNTPWD_INVALID")] EgecAccountpwdInvalid = 3,
    /// <summary>
    /// 账号正在使用
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_USING")] EgecAccountUsing = 4,
    /// <summary>
    /// 账号已封停
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_LOCKED")] EgecAccountLocked = 5,
    /// <summary>
    /// 账号登录成功
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_SUCCESS")] EgecAccountSuccess = 6,
    /// <summary>
    /// 账号KEY验证成功
    /// </summary>
    [pbr::OriginalName("EGEC_VERIFY_KEY_SUCCESS")] EgecVerifyKeySuccess = 7,
    /// <summary>
    /// 账号KEY验证失败
    /// </summary>
    [pbr::OriginalName("EGEC_VERIFY_KEY_FAIL")] EgecVerifyKeyFail = 8,
    /// <summary>
    /// 选择单服成功
    /// </summary>
    [pbr::OriginalName("EGEC_SELECTSERVER_SUCCESS")] EgecSelectserverSuccess = 9,
    /// <summary>
    /// 选择单服失败
    /// </summary>
    [pbr::OriginalName("EGEC_SELECTSERVER_FAIL")] EgecSelectserverFail = 10,
    /// <summary>
    /// 创建角色时角色名重复
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_EXIST")] EgecCharacterExist = 110,
    /// <summary>
    /// 创建角色时游戏区代码无效
    /// </summary>
    [pbr::OriginalName("EGEC_SVRZONEID_INVALID")] EgecSvrzoneidInvalid = 111,
    /// <summary>
    /// 创建角色时角色个数超出设定值（一个账号最多建4个角色）
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_NUMOUT")] EgecCharacterNumout = 112,
    /// <summary>
    /// 角色名无效（非法角色名）
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_INVALID")] EgecCharacterInvalid = 113,
    /// <summary>
    /// 角色不存在
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_NOTEXIST")] EgecCharacterNotexist = 114,
    /// <summary>
    /// 角色已在游戏中
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_USING")] EgecCharacterUsing = 115,
    /// <summary>
    /// 角色已封停
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_LOCKED")] EgecCharacterLocked = 116,
    /// <summary>
    /// 场景人数已满(领地XXX; 过于拥挤)
    /// </summary>
    [pbr::OriginalName("EGEC_ZONE_OVERLOAD")] EgecZoneOverload = 117,
    /// <summary>
    /// 玩家不在线
    /// </summary>
    [pbr::OriginalName("EGEC_NOT_ONLINE")] EgecNotOnline = 118,
    /// <summary>
    /// 玩家已经在队伍中了
    /// </summary>
    [pbr::OriginalName("EGEC_ALREAY_IN_TEAM")] EgecAlreayInTeam = 119,
    /// <summary>
    /// 无效的组队邀请
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_TEAM_INVITE")] EgecInvalidTeamInvite = 120,
    /// <summary>
    /// 队伍人数已满
    /// </summary>
    [pbr::OriginalName("EGEC_TEAM_FULL")] EgecTeamFull = 121,
    /// <summary>
    /// 更新邮件状态时出错
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_UPDATE_ERROR")] EgecMailUpdateError = 122,
    /// <summary>
    /// 邮件时收件人不存在
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_TONAME_INVALID")] EgecMailTonameInvalid = 123,
    /// <summary>
    /// 删除邮件失败
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_DELETE_ERROR")] EgecMailDeleteError = 124,
    /// <summary>
    /// 不能自己给自己发邮件
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_TOWNAME_EQUAL")] EgecMailTownameEqual = 125,
    /// <summary>
    /// 金钱不足
    /// </summary>
    [pbr::OriginalName("EGEC_LACK_MONEY")] EgecLackMoney = 126,
    /// <summary>
    /// 背包已满
    /// </summary>
    [pbr::OriginalName("EGEC_FULL_PACKAGE")] EgecFullPackage = 127,
    /// <summary>
    /// 无效的道具
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_ITEM")] EgecInvalidItem = 128,
    /// <summary>
    /// 无效的寄售ID
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_CONSIGNMENT")] EgecInvalidConsignment = 129,
    /// <summary>
    /// VIP点数不够
    /// </summary>
    [pbr::OriginalName("EGEC_NOT_ENOUGH_VIP")] EgecNotEnoughVip = 130,
    /// <summary>
    /// 等级不够
    /// </summary>
    [pbr::OriginalName("EGEC_NEED_LEVEL")] EgecNeedLevel = 131,
    /// <summary>
    /// 好友列表已满
    /// </summary>
    [pbr::OriginalName("EGEC_MAX_FRIEND_LIST")] EgecMaxFriendList = 132,
    /// <summary>
    /// 恶人列表已满
    /// </summary>
    [pbr::OriginalName("EGEC_MAX_ENEMY_LIST")] EgecMaxEnemyList = 133,
    /// <summary>
    /// 帮会人数达上限
    /// </summary>
    [pbr::OriginalName("EGEC_MAX_GANGS_LSIT")] EgecMaxGangsLsit = 134,
    /// <summary>
    /// 需要权限
    /// </summary>
    [pbr::OriginalName("EGEC_LIMITS_TO_RIGHTS")] EgecLimitsToRights = 135,
    /// <summary>
    /// 无效的帮会名称
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_GANGS_NAME")] EgecInvalidGangsName = 136,
    /// <summary>
    /// 角色已经是帮会成员了;不能再加入帮会了
    /// </summary>
    [pbr::OriginalName("EGEC_REPEAT_ENTER_GANGS")] EgecRepeatEnterGangs = 137,
    /// <summary>
    /// 角色不是指定帮会成员
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_GANGSMEMBER")] EgecInvalidGangsmember = 138,
    /// <summary>
    /// 会长不能离开帮会
    /// </summary>
    [pbr::OriginalName("EGEC_MASTER_LEAVE_GANGS")] EgecMasterLeaveGangs = 139,
    /// <summary>
    /// 指定帮会职务的人类超过该职务的最大数量
    /// </summary>
    [pbr::OriginalName("EGEC_GANGS_TITLE_OUTOF")] EgecGangsTitleOutof = 140,
    /// <summary>
    /// 无效的传送请求(传送门实际不存在;没有到达触发传送的条件等)
    /// </summary>
    [pbr::OriginalName("EGEC_ENTER_GATEWAY_FAILD")] EgecEnterGatewayFaild = 141,
    /// <summary>
    /// 还没有指派服务器管理该场景; 请稍等(游戏世界还处于混沌中...)
    /// </summary>
    [pbr::OriginalName("EGEC_NO_SERVER4ZONE")] EgecNoServer4Zone = 142,
    /// <summary>
    /// 无效的技能
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_SKILL")] EgecInvalidSkill = 143,
    /// <summary>
    /// 进入游戏成功
    /// </summary>
    [pbr::OriginalName("EGEC_ENTER_GAME_SUCCESS")] EgecEnterGameSuccess = 144,
    /// <summary>
    /// 创建公会成功
    /// </summary>
    [pbr::OriginalName("EGEC_CREATE_GUILD_SUCCESS")] EgecCreateGuildSuccess = 200,
    /// <summary>
    /// 加入公会成功
    /// </summary>
    [pbr::OriginalName("EGEC_JOIN_GUILD_SUCCESS")] EgecJoinGuildSuccess = 201,
    /// <summary>
    /// 离开公会成功
    /// </summary>
    [pbr::OriginalName("EGEC_LEAVE_GUILD_SUCCESS")] EgecLeaveGuildSuccess = 202,
  }

  public enum EGameMsgID {
    /// <summary>
    /// 位知
    /// </summary>
    [pbr::OriginalName("EGMI_UNKNOW")] EgmiUnknow = 0,
    /// <summary>
    /// 事件结果
    /// </summary>
    [pbr::OriginalName("EGMI_EVENT_RESULT")] EgmiEventResult = 1,
    /// <summary>
    /// 网关转发
    /// </summary>
    [pbr::OriginalName("EGMI_EVENT_TRANSPOND")] EgmiEventTranspond = 2,
    /// <summary>
    /// 想要关闭某个网络对象
    /// </summary>
    [pbr::OriginalName("EGMI_CLOSE_SOCKET")] EgmiCloseSocket = 3,
    [pbr::OriginalName("EGMI_MTL_WORLD_REGISTERED")] EgmiMtlWorldRegistered = 10,
    [pbr::OriginalName("EGMI_MTL_WORLD_UNREGISTERED")] EgmiMtlWorldUnregistered = 11,
    [pbr::OriginalName("EGMI_MTL_WORLD_REFRESH")] EgmiMtlWorldRefresh = 12,
    [pbr::OriginalName("EGMI_LTM_LOGIN_REGISTERED")] EgmiLtmLoginRegistered = 20,
    [pbr::OriginalName("EGMI_LTM_LOGIN_UNREGISTERED")] EgmiLtmLoginUnregistered = 21,
    [pbr::OriginalName("EGMI_LTM_LOGIN_REFRESH")] EgmiLtmLoginRefresh = 22,
    [pbr::OriginalName("EGMI_PTWG_PROXY_REGISTERED")] EgmiPtwgProxyRegistered = 30,
    [pbr::OriginalName("EGMI_PTWG_PROXY_UNREGISTERED")] EgmiPtwgProxyUnregistered = 31,
    [pbr::OriginalName("EGMI_PTWG_PROXY_REFRESH")] EgmiPtwgProxyRefresh = 32,
    [pbr::OriginalName("EGMI_GTW_GAME_REGISTERED")] EgmiGtwGameRegistered = 40,
    [pbr::OriginalName("EGMI_GTW_GAME_UNREGISTERED")] EgmiGtwGameUnregistered = 41,
    [pbr::OriginalName("EGMI_GTW_GAME_REFRESH")] EgmiGtwGameRefresh = 42,
    [pbr::OriginalName("EGMI_GTG_BROCASTMSG")] EgmiGtgBrocastmsg = 43,
    [pbr::OriginalName("EGMI_STS_NET_INFO")] EgmiStsNetInfo = 50,
    [pbr::OriginalName("EGMI_STS_HEART_BEAT")] EgmiStsHeartBeat = 100,
    /// <summary>
    ///////////////////////////////////////////////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LOGIN")] EgmiReqLogin = 101,
    /// <summary>
    /// 登陆帐号
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LOGIN")] EgmiAckLogin = 102,
    /// <summary>
    /// 登出帐号
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LOGOUT")] EgmiReqLogout = 103,
    /// <summary>
    /// 申请世界列表
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_WORLD_LIST")] EgmiReqWorldList = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_WORLD_LIST")] EgmiAckWorldList = 111,
    /// <summary>
    /// 申请连接到世界
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CONNECT_WORLD")] EgmiReqConnectWorld = 112,
    [pbr::OriginalName("EGMI_ACK_CONNECT_WORLD")] EgmiAckConnectWorld = 113,
    /// <summary>
    ///要求在此世界T人
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_KICK_CLIENT_INWORLD")] EgmiReqKickClientInworld = 114,
    /// <summary>
    /// 用KEY连接世界的网关
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CONNECT_KEY")] EgmiReqConnectKey = 120,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CONNECT_KEY")] EgmiAckConnectKey = 122,
    /// <summary>
    /// 选择一个单服
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SELECT_SERVER")] EgmiReqSelectServer = 130,
    /// <summary>
    /// 选择一个单服
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SELECT_SERVER")] EgmiAckSelectServer = 131,
    /// <summary>
    /// 申请角色列表
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_ROLE_LIST")] EgmiReqRoleList = 132,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ROLE_LIST")] EgmiAckRoleList = 133,
    /// <summary>
    /// 申请创建一个角色
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATE_ROLE")] EgmiReqCreateRole = 134,
    /// <summary>
    /// 申请删除一个角色
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_DELETE_ROLE")] EgmiReqDeleteRole = 135,
    /// <summary>
    /// 申请恢复一个角色
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_RECOVER_ROLE")] EgmiReqRecoverRole = 136,
    /// <summary>
    /// 申请进入游戏世界
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_ENTER_GAME")] EgmiReqEnterGame = 150,
    /// <summary>
    /// 回复进入了游戏世界成功
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ENTER_GAME")] EgmiAckEnterGame = 151,
    /// <summary>
    /// 申请离开游戏世界, 回到选人
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_GAME")] EgmiReqLeaveGame = 152,
    /// <summary>
    /// 回复,申请离开游戏世界
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_GAME")] EgmiAckLeaveGame = 153,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SWAP_GAME")] EgmiReqSwapGame = 154,
    /// <summary>
    /// 申请切换场景
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SWAP_SCENE")] EgmiReqSwapScene = 155,
    /// <summary>
    /// 回复切换场景结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SWAP_SCENE")] EgmiAckSwapScene = 156,
    /// <summary>
    /// 申请副本结算
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_END_BATTLE")] EgmiReqEndBattle = 157,
    /// <summary>
    /// 回复副本结算
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_END_BATTLE")] EgmiAckEndBattle = 158,
    /// <summary>
    /// 有对象进入
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ENTITY_ENTER")] EgmiAckEntityEnter = 200,
    /// <summary>
    /// 有对象出去
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ENTITY_LEAVE")] EgmiAckEntityLeave = 201,
    /// <summary>
    /// 有对象属性进入
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ENTITY_DATA_NODE_ENTER")] EgmiAckEntityDataNodeEnter = 202,
    /// <summary>
    /// 有对象表进入
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ENTITY_DATA_TABLE_ENTER")] EgmiAckEntityDataTableEnter = 203,
    /// <summary>
    /// 属性变更
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_NODE_DATA")] EgmiAckNodeData = 210,
    [pbr::OriginalName("EGMI_ACK_ADD_ROW")] EgmiAckAddRow = 220,
    [pbr::OriginalName("EGMI_ACK_REMOVE_ROW")] EgmiAckRemoveRow = 221,
    [pbr::OriginalName("EGMI_ACK_SWAP_ROW")] EgmiAckSwapRow = 222,
    [pbr::OriginalName("EGMI_ACK_TABLE_DATA")] EgmiAckTableData = 223,
    [pbr::OriginalName("EGMI_ACK_TABLE_CLEAR")] EgmiAckTableClear = 229,
    [pbr::OriginalName("EGMI_ACK_TABLE_SORT")] EgmiAckTableSort = 230,
    [pbr::OriginalName("EGMI_REQ_MOVE")] EgmiReqMove = 235,
    [pbr::OriginalName("EGMI_ACK_MOVE")] EgmiAckMove = 236,
    [pbr::OriginalName("EGMI_REQ_MOVE_IMMUNE")] EgmiReqMoveImmune = 237,
    [pbr::OriginalName("EGMI_ACK_MOVE_IMMUNE")] EgmiAckMoveImmune = 238,
    [pbr::OriginalName("EGMI_REQ_SKILL_OBJECTX")] EgmiReqSkillObjectx = 240,
    [pbr::OriginalName("EGMI_ACK_SKILL_OBJECTX")] EgmiAckSkillObjectx = 241,
    [pbr::OriginalName("EGMI_REQ_SKILL_POS")] EgmiReqSkillPos = 242,
    [pbr::OriginalName("EGMI_ACK_SKILL_POS")] EgmiAckSkillPos = 243,
    [pbr::OriginalName("EGMI_REQ_ITEM_OBJECT")] EgmiReqItemObject = 244,
    [pbr::OriginalName("EGMI_ACK_ITEM_OBJECT")] EgmiAckItemObject = 245,
    [pbr::OriginalName("EGMI_REQ_ITEM_POS")] EgmiReqItemPos = 246,
    [pbr::OriginalName("EGMI_ACK_ITEM_POS")] EgmiAckItemPos = 247,
    [pbr::OriginalName("EGMI_REQ_CHAT")] EgmiReqChat = 250,
    [pbr::OriginalName("EGMI_ACK_CHAT")] EgmiAckChat = 251,
    [pbr::OriginalName("EGMI_REQ_SALE_ITEM")] EgmiReqSaleItem = 252,
    [pbr::OriginalName("EGMI_REQ_SPLIT_ITEM")] EgmiReqSplitItem = 253,
    [pbr::OriginalName("EGMI_REQ_PRODUCE_ITEM")] EgmiReqProduceItem = 254,
    [pbr::OriginalName("EGMI_REQ_PICK_ITEM")] EgmiReqPickItem = 255,
    [pbr::OriginalName("EGMI_REQ_ACCEPT_TASK")] EgmiReqAcceptTask = 256,
    [pbr::OriginalName("EGMI_REQ_COMPELETE_TASK")] EgmiReqCompeleteTask = 257,
    /// <summary>
    /// 申请加入PVP
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_JOIN_PVP")] EgmiReqJoinPvp = 260,
    /// <summary>
    /// 申请离开PVP
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_EXIT_PVP")] EgmiReqExitPvp = 261,
    /// <summary>
    /// 通知开始PVP
    /// </summary>
    [pbr::OriginalName("EGMT_ACK_START_PVP")] EgmtAckStartPvp = 262,
    /// <summary>
    /// 查找对手(EBattleType)
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SEARCH_OPPNENT")] EgmiReqSearchOppnent = 280,
    /// <summary>
    /// 返回查找对手的信息(EBattleType)
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SEARCH_OPPNENT")] EgmiAckSearchOppnent = 281,
    /// <summary>
    /// 开始战斗(EBattleType)
    /// </summary>
    [pbr::OriginalName("EGMT_REQ_START_OPPNENT")] EgmtReqStartOppnent = 282,
    /// <summary>
    /// 开始战斗(EBattleType)
    /// </summary>
    [pbr::OriginalName("EGMT_ACK_START_OPPNENT")] EgmtAckStartOppnent = 283,
    /// <summary>
    /// 玩家上线通知
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ONLINE_NOTIFY")] EgmiAckOnlineNotify = 290,
    /// <summary>
    /// 玩家下线通知
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OFFLINE_NOTIFY")] EgmiAckOfflineNotify = 291,
    /// <summary>
    /// 申请创建公会
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATE_GUILD")] EgmiReqCreateGuild = 300,
    /// <summary>
    /// 创建公会结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CREATE_GUILD")] EgmiAckCreateGuild = 301,
    /// <summary>
    /// 申请加入公会
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_JOIN_GUILD")] EgmiReqJoinGuild = 302,
    /// <summary>
    /// 加入公会结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_JOIN_GUILD")] EgmiAckJoinGuild = 303,
    /// <summary>
    /// 申请离开公会
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_GUILD")] EgmiReqLeaveGuild = 304,
    /// <summary>
    /// 离开公会结果 
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_GUILD")] EgmiAckLeaveGuild = 305,
    /// <summary>
    /// 申请成员操作 
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_OPR_GUILD")] EgmiReqOprGuild = 306,
    /// <summary>
    /// 成员操作结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OPR_GUILD")] EgmiAckOprGuild = 307,
    /// <summary>
    /// 申请搜索公会
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SEARCH_GUILD")] EgmiReqSearchGuild = 308,
    /// <summary>
    /// 返回搜索公会	
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SEARCH_GUILD")] EgmiAckSearchGuild = 309,
    /// <summary>
    /// 申请公会操作 
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_OPR_GUILDINFO")] EgmiReqOprGuildinfo = 310,
    /// <summary>
    /// 公会操作结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OPR_GUILDINFO")] EgmiAckOprGuildinfo = 311,
    /// <summary>
    /// 申请公会副本
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_GUILDECTYPEINFO")] EgmiReqGuildectypeinfo = 312,
    /// <summary>
    /// 工会副本的信息
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_GUILDECTYPEINFO")] EgmiAckGuildectypeinfo = 313,
    /// <summary>
    /// 设置工会副本的信息
    /// </summary>
    [pbr::OriginalName("EGMI_SET_GUILDECTYPEINFO")] EgmiSetGuildectypeinfo = 314,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("EGMI_ReqEnterGuildEctype")] EgmiReqEnterGuildEctype = 315,
    /// <summary>
    /// 创建聊天ReqAckCreateChatGroup
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_CREATE_CHATGROUP")] EgecReqCreateChatgroup = 400,
    /// <summary>
    /// 创建聊天ReqAckCreateChatGroup
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_CREATE_CHATGROUP")] EgecAckCreateChatgroup = 401,
    /// <summary>
    /// 加入聊天ReqAckjoinChatGroup
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_JOIN_CHATGROUP")] EgecReqJoinChatgroup = 402,
    /// <summary>
    /// 加入聊天ReqAckjoinChatGroup
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_JOIN_CHATGROUP")] EgecAckJoinChatgroup = 403,
    /// <summary>
    /// 离开聊天ReqAckQuitChatGroup
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_LEAVE_CHATGROUP")] EgecReqLeaveChatgroup = 404,
    /// <summary>
    /// 离开聊天ReqAckQuitChatGroup
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_LEAVE_CHATGROUP")] EgecAckLeaveChatgroup = 405,
    /// <summary>
    /// 订阅聊天室ReqSubscriptionChatGroup
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SUBSCRIPTION_CHATGROUP")] EgecReqSubscriptionChatgroup = 406,
    /// <summary>
    /// 取消订阅聊天室ReqSubscriptionChatGroup
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_CANCELSUBSCRIPTION_CHATGROUP")] EgecReqCancelsubscriptionChatgroup = 407,
    /// <summary>
    /// 邀请进入聊天室
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_INVITE_CHATGROUP")] EgecReqInviteChatgroup = 408,
    /// <summary>
    /// 邀请进入聊天室
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_INVITE_CHATGROUP")] EgecAckInviteChatgroup = 409,
    /// <summary>
    /// 踢出聊天室
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_KICK_CHATGROUP")] EgecReqKickChatgroup = 410,
    /// <summary>
    /// 踢出聊天室
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_KICK_CHATGROUP")] EgecAckKickChatgroup = 411,
    /// <summary>
    /// 聊天室快速组队
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_CHATGROUP_TO_TEAM")] EgecReqChatgroupToTeam = 450,
    /// <summary>
    /// 聊天室快速组队	
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_CHATGROUP_TO_TEAM")] EgecAckChatgroupToTeam = 451,
    /// <summary>
    /// 装备强化
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_INTENSIFYLEVEL_TO_EQUIP")] EgecReqIntensifylevelToEquip = 500,
    /// <summary>
    /// 装备强化
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_INTENSIFYLEVEL_TO_EQUIP")] EgecAckIntensifylevelToEquip = 501,
    /// <summary>
    /// 装备打洞
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_HOLE_TO_EQUIP")] EgecReqHoleToEquip = 502,
    /// <summary>
    /// 装备打洞
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_HOLE_TO_EQUIP")] EgecAckHoleToEquip = 503,
    /// <summary>
    /// 装备镶嵌
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_INLAYSTONE_TO_EQUIP")] EgecReqInlaystoneToEquip = 504,
    /// <summary>
    /// 装备镶嵌
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_INLAYSTONE_TO_EQUIP")] EgecAckInlaystoneToEquip = 505,
    /// <summary>
    /// 装备附魔
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_ELEMENTLEVEL_TO_EQUIP")] EgecReqElementlevelToEquip = 506,
    /// <summary>
    /// 装备附魔
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_ELEMENTLEVEL_TO_EQUIP")] EgecAckElementlevelToEquip = 507,
    /// <summary>
    /// 战斗武将
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SET_FIGHT_HERO")] EgecReqSetFightHero = 508,
    /// <summary>
    /// 装备创戴
    /// </summary>
    [pbr::OriginalName("EGEC_WEAR_EQUIP")] EgecWearEquip = 509,
    /// <summary>
    /// 装备卸载
    /// </summary>
    [pbr::OriginalName("EGEC_TAKEOFF_EQUIP")] EgecTakeoffEquip = 510,
    /// <summary>
    /// 申请挖次矿（地块）
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_MINING_TITLE")] EgecReqMiningTitle = 600,
    /// <summary>
    /// 发送邮件
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SEND_MAIL")] EgecReqSendMail = 700,
    /// <summary>
    /// 领取邮件中的奖励(包含道具或者钻石等非道具的东西)
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_DRAW_MAIL")] EgecReqDrawMail = 701,
    /// <summary>
    /// 删除邮件
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_DELETE_MAIL")] EgecReqDeleteMail = 702,
    /// <summary>
    ///对象clone
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_ENTRY")] EgmiAckCloneObjectEntry = 800,
    /// <summary>
    /// 有对象出去
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_LEAVE")] EgmiAckCloneObjectLeave = 801,
    /// <summary>
    /// 有对象属性进入
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_PROPERTY_ENTRY")] EgmiAckCloneObjectPropertyEntry = 802,
    /// <summary>
    /// 有对象表进入
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_RECORD_ENTRY")] EgmiAckCloneObjectRecordEntry = 803,
    /// <summary>
    /// 属性变更
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_INT")] EgmiAckClonePropertyInt = 810,
    /// <summary>
    /// 属性变更
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_FLOAT")] EgmiAckClonePropertyFloat = 811,
    /// <summary>
    /// 属性变更
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_STRING")] EgmiAckClonePropertyString = 812,
    /// <summary>
    /// 属性变更
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_DOUBLE")] EgmiAckClonePropertyDouble = 813,
    /// <summary>
    /// 属性变更
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_OBJECT")] EgmiAckClonePropertyObject = 814,
    [pbr::OriginalName("EGMI_ACK_CLONE_ADD_ROW")] EgmiAckCloneAddRow = 820,
    [pbr::OriginalName("EGMI_ACK_CLONE_REMOVE_ROW")] EgmiAckCloneRemoveRow = 821,
    [pbr::OriginalName("EGMI_ACK_CLONE_SWAP_ROW")] EgmiAckCloneSwapRow = 822,
    [pbr::OriginalName("EGMI_ACK_CLONE_RECORD_INT")] EgmiAckCloneRecordInt = 823,
    [pbr::OriginalName("EGMI_ACK_CLONE_RECORD_FLOAT")] EgmiAckCloneRecordFloat = 824,
    [pbr::OriginalName("EGMI_ACK_CLONE_RECORD_DOUBLE")] EgmiAckCloneRecordDouble = 825,
    [pbr::OriginalName("EGMI_ACK_CLONE_RECORD_STRING")] EgmiAckCloneRecordString = 826,
    [pbr::OriginalName("EGMI_ACK_CLONE_RECORD_OBJECT")] EgmiAckCloneRecordObject = 827,
    [pbr::OriginalName("EGMI_ACK_CLONE_RECORD_CLEAR")] EgmiAckCloneRecordClear = 828,
    [pbr::OriginalName("EGMI_ACK_CLONE_RECORD_SORT")] EgmiAckCloneRecordSort = 829,
    /// <summary>
    /// 申请转服
    /// </summary>
    [pbr::OriginalName("EGMI_REQSWICHSERVER")] EgmiReqswichserver = 840,
    /// <summary>
    /// 申请转服
    /// </summary>
    [pbr::OriginalName("EGMI_ACKSWICHSERVER")] EgmiAckswichserver = 841,
    /// <summary>
    /// 申请创建队伍
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATE_TEAM")] EgmiReqCreateTeam = 860,
    /// <summary>
    /// 创建队伍结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CREATE_TEAM")] EgmiAckCreateTeam = 861,
    /// <summary>
    /// 申请加入队伍
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_JOIN_TEAM")] EgmiReqJoinTeam = 862,
    /// <summary>
    /// 加入队伍结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_JOIN_TEAM")] EgmiAckJoinTeam = 863,
    /// <summary>
    /// 申请离开队伍
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_TEAM")] EgmiReqLeaveTeam = 864,
    /// <summary>
    /// 离开队伍结果 
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_TEAM")] EgmiAckLeaveTeam = 865,
    /// <summary>
    /// 邀请加入队伍
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_INVITE_TEAM")] EgmiReqInviteTeam = 866,
    /// <summary>
    /// 操作成员
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_OPRMEMBER_TEAM")] EgmiReqOprmemberTeam = 867,
    /// <summary>
    /// 操作成员 
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OPRMEMBER_TEAM")] EgmiAckOprmemberTeam = 868,
    /// <summary>
    /// 组队进副本 
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_TEAM_ENTER_ECTYPE")] EgmiReqTeamEnterEctype = 869,
    /// <summary>
    /// 组队进副本
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_TEAM_ENTER_ECTYPE")] EgmiAckTeamEnterEctype = 870,
    /// <summary>
    //////////////////////MapModule/////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_MAP_GRID_INFO")] EgmiReqMapGridInfo = 900,
    /// <summary>
    /// 返回查看格子地图	
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_MAP_GRID_INFO")] EgmiAckMapGridInfo = 901,
    /// <summary>
    /// 申请大地图信息
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_BIG_MAP_INFO")] EgmiReqBigMapInfo = 902,
    /// <summary>
    /// 返回大地图
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_BIG_MAP_INFO")] EgmiAckBigMapInfo = 903,
    /// <summary>
    /// 申请入驻
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_HOLD_MAP_GRID")] EgmiReqHoldMapGrid = 910,
    /// <summary>
    /// 返回入驻结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_HOLD_MAP_GRID")] EgmiAckHoldMapGrid = 911,
    /// <summary>
    /// 申请留言
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_MSG_MAP_GRID")] EgmiReqLeaveMsgMapGrid = 912,
    /// <summary>
    /// 返回留言结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_MSG_MAP_GRID")] EgmiAckLeaveMsgMapGrid = 913,
    /// <summary>
    /// 申请领取地图奖励
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_GET_MAP_GRID_AWARD")] EgmiReqGetMapGridAward = 914,
    /// <summary>
    /// 返回领取地图奖励
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_GET_MAP_GRID_AWARD")] EgmiAckGetMapGridAward = 915,
    /// <summary>
    /// 申请地图狩猎
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_MAP_GRID_HUNTING")] EgmiReqMapGridHunting = 916,
    /// <summary>
    /// 返回结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_MAP_GRID_HUNTING")] EgmiAckMapGridHunting = 917,
    /// <summary>
    /// 申请地图争霸
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_MAP_GRID_KING_WAR")] EgmiReqMapGridKingWar = 918,
    /// <summary>
    /// 返回结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_MAP_GRID_KING_WAR")] EgmiAckMapGridKingWar = 919,
    /// <summary>
    //////////////////////GM MSG/////////////////////////////////////订阅
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_INT")] EgmiReqCmdPropertyInt = 1000,
    /// <summary>
    /// GM命令修改修改字符串
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_STR")] EgmiReqCmdPropertyStr = 1001,
    /// <summary>
    /// GM命令
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_OBJECT")] EgmiReqCmdPropertyObject = 1002,
    /// <summary>
    /// GM命令
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_FLOAT")] EgmiReqCmdPropertyFloat = 1003,
    /// <summary>
    /// GM命令修改表整形
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_INT")] EgmiReqCmdRecordInt = 1004,
    /// <summary>
    /// GM命令修改修改表字符串
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_STR")] EgmiReqCmdRecordStr = 1005,
    /// <summary>
    /// GM命令修改
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_OBJECT")] EgmiReqCmdRecordObject = 1006,
    /// <summary>
    /// GM命令修改
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_FLOAT")] EgmiReqCmdRecordFloat = 1007,
    /// <summary>
    /// 其他GM修改
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_NORMAL")] EgmiReqCmdNormal = 1008,
    /// <summary>
    /// 申请匹配pvp
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_PVPAPPLYMACTCH")] EgmiReqPvpapplymactch = 1100,
    /// <summary>
    /// 申请匹配pvp
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_PVPAPPLYMACTCH")] EgmiAckPvpapplymactch = 1101,
    /// <summary>
    /// 申请pvp副本
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATEPVPECTYPE")] EgmiReqCreatepvpectype = 1102,
    /// <summary>
    /// 返回pvp副本的信息，并拉人
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CREATEPVPECTYPE")] EgmiAckCreatepvpectype = 1103,
    /// <summary>
    //////////////////////Base SLG MSG/////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_BUY_FORM_SHOP")] EgmiReqBuyFormShop = 10000,
    /// <summary>
    ///返回商店种植建筑结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_BUY_FORM_SHOP")] EgmiAckBuyFormShop = 10001,
    /// <summary>
    ///申请移动建筑
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_MOVE_BUILD_OBJECT")] EgmiReqMoveBuildObject = 10002,
    /// <summary>
    ///返回移动建筑结果
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_MOVE_BUILD_OBJECT")] EgmiAckMoveBuildObject = 10003,
    /// <summary>
    ///申请建筑升级
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_UP_BUILD_LVL")] EgmiReqUpBuildLvl = 10101,
    /// <summary>
    ///申请造兵&amp;药水&amp;等
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATE_ITEM")] EgmiReqCreateItem = 10102,
    /// <summary>
    ///申请建筑操作
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_BUILD_OPERATE")] EgmiReqBuildOperate = 10103,
  }

  /// <summary>
  //////////////////////////道具系统相关//////////////////////////////////////////////////////////////////////////
  /// </summary>
  public enum EItemType {
    /// <summary>
    /// 装备
    /// </summary>
    [pbr::OriginalName("EIT_EQUIP")] EitEquip = 0,
    /// <summary>
    /// 宝石
    /// </summary>
    [pbr::OriginalName("EIT_GEM")] EitGem = 1,
    /// <summary>
    /// 消耗品
    /// </summary>
    [pbr::OriginalName("EIT_ITEM")] EitItem = 2,
    /// <summary>
    /// 卡牌
    /// </summary>
    [pbr::OriginalName("EIT_CARD")] EitCard = 3,
    /// <summary>
    /// 令牌
    /// </summary>
    [pbr::OriginalName("EIT_TOKEN")] EitToken = 4,
  }

  /// <summary>
  ///装备子类型(归属类型)
  /// </summary>
  public enum EGameEquipSubType {
    /// <summary>
    /// 武器
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_WEAPON")] EquiptypeWeapon = 0,
    /// <summary>
    /// 头盔
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_HELMET")] EquiptypeHelmet = 1,
    /// <summary>
    /// 胸甲
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_ARMOR")] EquiptypeArmor = 2,
    /// <summary>
    /// 护腕	
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_WRIST")] EquiptypeWrist = 3,
    /// <summary>
    /// 裤子	
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_PANT")] EquiptypePant = 4,
    /// <summary>
    /// 靴子
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_BOOT")] EquiptypeBoot = 5,
  }

  /// <summary>
  ///宝石子类型	
  /// </summary>
  public enum EGameGemSubType {
    /// <summary>
    /// 攻击宝石
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_ATK")] EggstypeGemAtk = 0,
    /// <summary>
    /// 防御宝石
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_DEF")] EggstypeGemDef = 1,
    /// <summary>
    /// 电宝石
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_THUNDER")] EggstypeGemThunder = 2,
    /// <summary>
    /// 火宝石
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_FIRE")] EggstypeGemFire = 3,
    /// <summary>
    /// 雷宝石
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_LIGHT")] EggstypeGemLight = 4,
    /// <summary>
    /// 风宝石
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_WIND")] EggstypeGemWind = 5,
    /// <summary>
    /// 冰冻宝石
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_ICE")] EggstypeGemIce = 6,
    /// <summary>
    /// 毒宝石	
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_POISON")] EggstypeGemPoison = 7,
  }

  public enum EGameItemSubType {
    /// <summary>
    /// 圣水
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_WATER")] EgitItemWater = 0,
    /// <summary>
    /// 钻石 
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_DIAMOND")] EgitItemDiamond = 1,
    /// <summary>
    /// 金币
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_CURRENCY")] EgitItemCurrency = 2,
    /// <summary>
    /// EXP
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_EXP")] EgitItemExp = 3,
    /// <summary>
    /// 生命药水
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_HP")] EgitItemHp = 4,
    /// <summary>
    /// 魔法药水
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_MP")] EgitItemMp = 5,
    /// <summary>
    /// 体力药水
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_SP")] EgitItemSp = 6,
    /// <summary>
    /// 礼包
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_PACK")] EgitItemPack = 7,
  }

  public enum EGameCardSubType {
    [pbr::OriginalName("EGCST_NONE")] EgcstNone = 0,
    /// <summary>
    ///力量	
    /// </summary>
    [pbr::OriginalName("EGCST_STRENGTH")] EgcstStrength = 1,
    /// <summary>
    ///敏捷
    /// </summary>
    [pbr::OriginalName("EGCST_AGILITY")] EgcstAgility = 2,
    /// <summary>
    ///智力
    /// </summary>
    [pbr::OriginalName("EGCST_INTELLIGENCE")] EgcstIntelligence = 3,
  }

  public enum EGameTokenSubType {
    /// <summary>
    /// 重生道具(消耗此物品时得到某种待遇)
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_REBORN")] EgtstTokenReborn = 0,
    /// <summary>
    /// 移动位置(传送到新手村)(消耗此物品时得到某种待遇)
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_POSITION")] EgtstTokenPosition = 1,
    /// <summary>
    /// 赏金令
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_BOUNTY")] EgtstTokenBounty = 2,
    /// <summary>
    /// 活动令牌
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_ACTIVITY")] EgtstTokenActivity = 3,
  }

  /// <summary>
  ///道具时间类型
  /// </summary>
  public enum EGameItemExpiredType {
    /// <summary>
    /// 永不过期类型
    /// </summary>
    [pbr::OriginalName("EGIET_NONE")] EgietNone = 0,
    /// <summary>
    /// 使用次数, 变形魔杖,变0道具要消失(普通物品数量)
    /// </summary>
    [pbr::OriginalName("EGIET_USE_TIMES")] EgietUseTimes = 1,
    /// <summary>
    /// 真实的时间流逝(秒),适合时装,礼包,饰品(写死1天1周)
    /// </summary>
    [pbr::OriginalName("EGIET_REAL_TIME")] EgietRealTime = 2,
    [pbr::OriginalName("EGIET_END_INDEX")] EgietEndIndex = 3,
  }

  public enum EDrawDropItemState {
    /// <summary>
    /// 初始状态
    /// </summary>
    [pbr::OriginalName("E_DRAW_STATE_NONE")] EDrawStateNone = 0,
    /// <summary>
    /// 可获得
    /// </summary>
    [pbr::OriginalName("E_DRAW_STATE_GAIN")] EDrawStateGain = 1,
    /// <summary>
    /// 已领取
    /// </summary>
    [pbr::OriginalName("E_DRAW_STATE_RECV")] EDrawStateRecv = 2,
  }

  /// <summary>
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  /// 公会成员权限
  /// </summary>
  public enum EGuildPowerType {
    /// <summary>
    /// 普通成员
    /// </summary>
    [pbr::OriginalName("GUILD_POWER_TYPE_NORMAL")] GuildPowerTypeNormal = 0,
    /// <summary>
    /// 副会长
    /// </summary>
    [pbr::OriginalName("GUILD_POWER_TYPE_VICE_PRESIDENT")] GuildPowerTypeVicePresident = 1,
    /// <summary>
    /// 会长
    /// </summary>
    [pbr::OriginalName("GUILD_POWER_TYPE_PRESIDENT")] GuildPowerTypePresident = 2,
  }

  /// <summary>
  /// 任务状态
  /// </summary>
  public enum ETaskState {
    /// <summary>
    /// 任务进行中
    /// </summary>
    [pbr::OriginalName("TASK_IN_PROCESS")] TaskInProcess = 0,
    /// <summary>
    /// 任务完成
    /// </summary>
    [pbr::OriginalName("TASK_DONE")] TaskDone = 1,
    /// <summary>
    /// 领取过任务奖励了
    /// </summary>
    [pbr::OriginalName("TASK_DRAW_AWARD")] TaskDrawAward = 2,
    /// <summary>
    /// 任务结束
    /// </summary>
    [pbr::OriginalName("TASK_FINISH")] TaskFinish = 3,
  }

  /// <summary>
  /// 任务类型
  /// </summary>
  public enum ETaskType {
    /// <summary>
    /// 主角升级到某个等级
    /// </summary>
    [pbr::OriginalName("TASK_LEVEL_UPDATE_SOME_LEVEL")] TaskLevelUpdateSomeLevel = 0,
    /// <summary>
    /// 通过某个副本
    /// </summary>
    [pbr::OriginalName("TASK_PASS_ECTYPE")] TaskPassEctype = 1,
    /// <summary>
    /// 通过任意副本多少次
    /// </summary>
    [pbr::OriginalName("TASK_PASS_ECTYPE_COUNT")] TaskPassEctypeCount = 2,
    /// <summary>
    /// 通过某类副本多少次
    /// </summary>
    [pbr::OriginalName("TASK_PASS_SOME_TYPE_ECTYPE_COUNT")] TaskPassSomeTypeEctypeCount = 3,
    /// <summary>
    /// 升级技能多少次
    /// </summary>
    [pbr::OriginalName("TASK_UPDATE_SKILL_COUNT")] TaskUpdateSkillCount = 4,
    /// <summary>
    /// 消费多少金币
    /// </summary>
    [pbr::OriginalName("TASK_CONSUME_MONEY")] TaskConsumeMoney = 5,
    /// <summary>
    /// 消费多少钻石
    /// </summary>
    [pbr::OriginalName("TASK_CONSUME_DIAMOND")] TaskConsumeDiamond = 6,
    /// <summary>
    /// 参加竞技场多少次
    /// </summary>
    [pbr::OriginalName("TASK_ARENA_COUNT")] TaskArenaCount = 7,
    /// <summary>
    /// 累计杀怪多少只
    /// </summary>
    [pbr::OriginalName("TASK_KILL_MONSTER_COUNT")] TaskKillMonsterCount = 8,
    /// <summary>
    /// 杀死某个特定怪度多少只
    /// </summary>
    [pbr::OriginalName("TASK_KILL_SOME_MONSTER_COUNT")] TaskKillSomeMonsterCount = 9,
  }

  /// <summary>
  /// 战斗类型
  /// </summary>
  public enum EBattleType {
    /// <summary>
    /// 主角单人打副本
    /// </summary>
    [pbr::OriginalName("BATTLE_SINGLE")] BattleSingle = 0,
    /// <summary>
    /// 多人打副本
    /// </summary>
    [pbr::OriginalName("BATTLE_PVE_TEAM")] BattlePveTeam = 1,
  }

  public enum ERankType {
    [pbr::OriginalName("ERT_PLAYER_NONE")] ErtPlayerNone = 0,
    [pbr::OriginalName("ERT_PLAYER_LEVEL")] ErtPlayerLevel = 1,
    [pbr::OriginalName("ERT_FIGHT_VALUE")] ErtFightValue = 2,
    [pbr::OriginalName("ERT_PLAYER_MONEY")] ErtPlayerMoney = 3,
    [pbr::OriginalName("ERT_GUILD_LEVEL")] ErtGuildLevel = 4,
    [pbr::OriginalName("ERT_GUILD_KINGSOURCE")] ErtGuildKingsource = 5,
  }

  /// <summary>
  ///NCPTypenpc的类型
  /// </summary>
  public enum ENPCType {
    /// <summary>
    /// 普通怪
    /// </summary>
    [pbr::OriginalName("ENPCTYPE_NORMAL")] Normal = 0,
    /// <summary>
    /// 英雄
    /// </summary>
    [pbr::OriginalName("ENPCTYPE_HERO")] Hero = 1,
    /// <summary>
    /// 炮塔
    /// </summary>
    [pbr::OriginalName("ENPCTYPE_TURRET")] Turret = 2,
  }

  /// <summary>
  ///PropertyType 属性的类型
  /// </summary>
  public enum EPropertyType {
    /// <summary>
    ///无
    /// </summary>
    [pbr::OriginalName("EPT_NONE")] EptNone = 0,
    /// <summary>
    ///力量	
    /// </summary>
    [pbr::OriginalName("EPT_STRENGTH")] EptStrength = 1,
    /// <summary>
    ///敏捷
    /// </summary>
    [pbr::OriginalName("EPT_AGILITY")] EptAgility = 2,
    /// <summary>
    ///智力
    /// </summary>
    [pbr::OriginalName("EPT_INTELLIGENCE")] EptIntelligence = 3,
  }

  /// <summary>
  ///元素类型
  /// </summary>
  public enum EGameElementType {
    /// <summary>
    /// 火
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_FIRE")] EelementtypeFire = 0,
    /// <summary>
    /// 雷电
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_LIGHT")] EelementtypeLight = 1,
    /// <summary>
    /// 风
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_WIND")] EelementtypeWind = 2,
    /// <summary>
    /// 冰冻
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_ICE")] EelementtypeIce = 3,
    /// <summary>
    /// 毒	
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_POISON")] EelementtypePoison = 4,
  }

  #endregion

}

#endregion Designer generated code
