//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AFMsgBase.proto
// Note: requires additional types generated from: AFDefine.proto
namespace AFMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ident")]
  public partial class Ident : global::ProtoBuf.IExtensible
  {
    public Ident() {}
    
    private long _high;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long high
    {
      get { return _high; }
      set { _high = value; }
    }
    private long _low;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long low
    {
      get { return _low; }
      set { _low = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Point3D")]
  public partial class Point3D : global::ProtoBuf.IExtensible
  {
    public Point3D() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropertyPBData")]
  public partial class PropertyPBData : global::ProtoBuf.IExtensible
  {
    public PropertyPBData() {}
    
    private byte[] _property_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"property_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] property_name
    {
      get { return _property_name; }
      set { _property_name = value; }
    }
    private int _ndataType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ndataType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ndataType
    {
      get { return _ndataType; }
      set { _ndataType = value; }
    }
    private bool _mbValue = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mbValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool mbValue
    {
      get { return _mbValue; }
      set { _mbValue = value; }
    }
    private int _mnValue = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mnValue
    {
      get { return _mnValue; }
      set { _mnValue = value; }
    }
    private long _mn64Value = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mn64Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long mn64Value
    {
      get { return _mn64Value; }
      set { _mn64Value = value; }
    }
    private float _mfValue = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mfValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float mfValue
    {
      get { return _mfValue; }
      set { _mfValue = value; }
    }
    private double _mdValue = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mdValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double mdValue
    {
      get { return _mdValue; }
      set { _mdValue = value; }
    }
    private byte[] _mstrValue = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mstrValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] mstrValue
    {
      get { return _mstrValue; }
      set { _mstrValue = value; }
    }
    private long _mpVaule = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"mpVaule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long mpVaule
    {
      get { return _mpVaule; }
      set { _mpVaule = value; }
    }
    private byte[] _mpUserData = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"mpUserData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] mpUserData
    {
      get { return _mpUserData; }
      set { _mpUserData = value; }
    }
    private AFMsg.Ident _mGuid = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"mGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AFMsg.Ident mGuid
    {
      get { return _mGuid; }
      set { _mGuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecordPBData")]
  public partial class RecordPBData : global::ProtoBuf.IExtensible
  {
    public RecordPBData() {}
    
    private int _row;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int row
    {
      get { return _row; }
      set { _row = value; }
    }
    private int _col;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int col
    {
      get { return _col; }
      set { _col = value; }
    }
    private int _ndataType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ndataType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ndataType
    {
      get { return _ndataType; }
      set { _ndataType = value; }
    }
    private bool _mbValue = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mbValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool mbValue
    {
      get { return _mbValue; }
      set { _mbValue = value; }
    }
    private int _mnValue = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mnValue
    {
      get { return _mnValue; }
      set { _mnValue = value; }
    }
    private long _mn64Value = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mn64Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long mn64Value
    {
      get { return _mn64Value; }
      set { _mn64Value = value; }
    }
    private float _mfValue = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mfValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float mfValue
    {
      get { return _mfValue; }
      set { _mfValue = value; }
    }
    private double _mdValue = default(double);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mdValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double mdValue
    {
      get { return _mdValue; }
      set { _mdValue = value; }
    }
    private byte[] _mstrValue = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"mstrValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] mstrValue
    {
      get { return _mstrValue; }
      set { _mstrValue = value; }
    }
    private long _mpVaule = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"mpVaule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long mpVaule
    {
      get { return _mpVaule; }
      set { _mpVaule = value; }
    }
    private byte[] _mpUserData = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"mpUserData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] mpUserData
    {
      get { return _mpUserData; }
      set { _mpUserData = value; }
    }
    private AFMsg.Ident _mGuid = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"mGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AFMsg.Ident mGuid
    {
      get { return _mGuid; }
      set { _mGuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBData")]
  public partial class PBData : global::ProtoBuf.IExtensible
  {
    public PBData() {}
    
    private int _ndataType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ndataType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ndataType
    {
      get { return _ndataType; }
      set { _ndataType = value; }
    }
    private bool _mbValue = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mbValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool mbValue
    {
      get { return _mbValue; }
      set { _mbValue = value; }
    }
    private int _mnValue = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mnValue
    {
      get { return _mnValue; }
      set { _mnValue = value; }
    }
    private long _mn64Value = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mn64Value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long mn64Value
    {
      get { return _mn64Value; }
      set { _mn64Value = value; }
    }
    private float _mfValue = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mfValue", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float mfValue
    {
      get { return _mfValue; }
      set { _mfValue = value; }
    }
    private double _mdValue = default(double);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mdValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double mdValue
    {
      get { return _mdValue; }
      set { _mdValue = value; }
    }
    private byte[] _mstrValue = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mstrValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] mstrValue
    {
      get { return _mstrValue; }
      set { _mstrValue = value; }
    }
    private long _mpVaule = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mpVaule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long mpVaule
    {
      get { return _mpVaule; }
      set { _mpVaule = value; }
    }
    private byte[] _mpUserData = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"mpUserData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] mpUserData
    {
      get { return _mpUserData; }
      set { _mpUserData = value; }
    }
    private AFMsg.Ident _mGuid = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"mGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AFMsg.Ident mGuid
    {
      get { return _mGuid; }
      set { _mGuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DataListPBData")]
  public partial class DataListPBData : global::ProtoBuf.IExtensible
  {
    public DataListPBData() {}
    
    private readonly global::System.Collections.Generic.List<AFMsg.PBData> _data_list = new global::System.Collections.Generic.List<AFMsg.PBData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"data_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.PBData> data_list
    {
      get { return _data_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecordAddRowStruct")]
  public partial class RecordAddRowStruct : global::ProtoBuf.IExtensible
  {
    public RecordAddRowStruct() {}
    
    private int _row;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int row
    {
      get { return _row; }
      set { _row = value; }
    }
    private readonly global::System.Collections.Generic.List<AFMsg.RecordPBData> _record_data_list = new global::System.Collections.Generic.List<AFMsg.RecordPBData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"record_data_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.RecordPBData> record_data_list
    {
      get { return _record_data_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectRecordBase")]
  public partial class ObjectRecordBase : global::ProtoBuf.IExtensible
  {
    public ObjectRecordBase() {}
    
    private byte[] _record_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"record_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] record_name
    {
      get { return _record_name; }
      set { _record_name = value; }
    }
    private readonly global::System.Collections.Generic.List<AFMsg.RecordAddRowStruct> _row_struct = new global::System.Collections.Generic.List<AFMsg.RecordAddRowStruct>();
    [global::ProtoBuf.ProtoMember(2, Name=@"row_struct", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.RecordAddRowStruct> row_struct
    {
      get { return _row_struct; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectPropertyList")]
  public partial class ObjectPropertyList : global::ProtoBuf.IExtensible
  {
    public ObjectPropertyList() {}
    
    private AFMsg.Ident _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AFMsg.Ident player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<AFMsg.PropertyPBData> _property_data_list = new global::System.Collections.Generic.List<AFMsg.PropertyPBData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"property_data_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.PropertyPBData> property_data_list
    {
      get { return _property_data_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MultiObjectPropertyList")]
  public partial class MultiObjectPropertyList : global::ProtoBuf.IExtensible
  {
    public MultiObjectPropertyList() {}
    
    private readonly global::System.Collections.Generic.List<AFMsg.ObjectPropertyList> _multi_player_property = new global::System.Collections.Generic.List<AFMsg.ObjectPropertyList>();
    [global::ProtoBuf.ProtoMember(1, Name=@"multi_player_property", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.ObjectPropertyList> multi_player_property
    {
      get { return _multi_player_property; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectRecordList")]
  public partial class ObjectRecordList : global::ProtoBuf.IExtensible
  {
    public ObjectRecordList() {}
    
    private AFMsg.Ident _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AFMsg.Ident player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<AFMsg.ObjectRecordBase> _record_list = new global::System.Collections.Generic.List<AFMsg.ObjectRecordBase>();
    [global::ProtoBuf.ProtoMember(2, Name=@"record_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.ObjectRecordBase> record_list
    {
      get { return _record_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MultiObjectRecordList")]
  public partial class MultiObjectRecordList : global::ProtoBuf.IExtensible
  {
    public MultiObjectRecordList() {}
    
    private readonly global::System.Collections.Generic.List<AFMsg.ObjectRecordList> _multi_player_record = new global::System.Collections.Generic.List<AFMsg.ObjectRecordList>();
    [global::ProtoBuf.ProtoMember(1, Name=@"multi_player_record", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.ObjectRecordList> multi_player_record
    {
      get { return _multi_player_record; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectPropertyPBData")]
  public partial class ObjectPropertyPBData : global::ProtoBuf.IExtensible
  {
    public ObjectPropertyPBData() {}
    
    private AFMsg.Ident _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AFMsg.Ident player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<AFMsg.PropertyPBData> _property_list = new global::System.Collections.Generic.List<AFMsg.PropertyPBData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"property_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.PropertyPBData> property_list
    {
      get { return _property_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectRecordPBData")]
  public partial class ObjectRecordPBData : global::ProtoBuf.IExtensible
  {
    public ObjectRecordPBData() {}
    
    private AFMsg.Ident _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AFMsg.Ident player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private byte[] _record_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"record_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] record_name
    {
      get { return _record_name; }
      set { _record_name = value; }
    }
    private readonly global::System.Collections.Generic.List<AFMsg.RecordPBData> _record_list = new global::System.Collections.Generic.List<AFMsg.RecordPBData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"record_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.RecordPBData> record_list
    {
      get { return _record_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectRecordSwap")]
  public partial class ObjectRecordSwap : global::ProtoBuf.IExtensible
  {
    public ObjectRecordSwap() {}
    
    private AFMsg.Ident _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AFMsg.Ident player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private byte[] _origin_record_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"origin_record_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] origin_record_name
    {
      get { return _origin_record_name; }
      set { _origin_record_name = value; }
    }
    private byte[] _target_record_name = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"target_record_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] target_record_name
    {
      get { return _target_record_name; }
      set { _target_record_name = value; }
    }
    private int _row_origin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"row_origin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int row_origin
    {
      get { return _row_origin; }
      set { _row_origin = value; }
    }
    private int _row_target;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"row_target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int row_target
    {
      get { return _row_target; }
      set { _row_target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectRecordAddRow")]
  public partial class ObjectRecordAddRow : global::ProtoBuf.IExtensible
  {
    public ObjectRecordAddRow() {}
    
    private AFMsg.Ident _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AFMsg.Ident player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private byte[] _record_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"record_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] record_name
    {
      get { return _record_name; }
      set { _record_name = value; }
    }
    private readonly global::System.Collections.Generic.List<AFMsg.RecordAddRowStruct> _row_data = new global::System.Collections.Generic.List<AFMsg.RecordAddRowStruct>();
    [global::ProtoBuf.ProtoMember(3, Name=@"row_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.RecordAddRowStruct> row_data
    {
      get { return _row_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectRecordRemove")]
  public partial class ObjectRecordRemove : global::ProtoBuf.IExtensible
  {
    public ObjectRecordRemove() {}
    
    private AFMsg.Ident _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AFMsg.Ident player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private byte[] _record_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"record_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] record_name
    {
      get { return _record_name; }
      set { _record_name = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _remove_row = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"remove_row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> remove_row
    {
      get { return _remove_row; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerPropertyBase")]
  public partial class PlayerPropertyBase : global::ProtoBuf.IExtensible
  {
    public PlayerPropertyBase() {}
    
    private readonly global::System.Collections.Generic.List<AFMsg.PropertyPBData> _property_data_list = new global::System.Collections.Generic.List<AFMsg.PropertyPBData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"property_data_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.PropertyPBData> property_data_list
    {
      get { return _property_data_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRecordBase")]
  public partial class PlayerRecordBase : global::ProtoBuf.IExtensible
  {
    public PlayerRecordBase() {}
    
    private string _record_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"record_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string record_name
    {
      get { return _record_name; }
      set { _record_name = value; }
    }
    private readonly global::System.Collections.Generic.List<AFMsg.RecordPBData> _record_data_list = new global::System.Collections.Generic.List<AFMsg.RecordPBData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"record_data_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.RecordPBData> record_data_list
    {
      get { return _record_data_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRecordList")]
  public partial class PlayerRecordList : global::ProtoBuf.IExtensible
  {
    public PlayerRecordList() {}
    
    private readonly global::System.Collections.Generic.List<AFMsg.PlayerRecordBase> _record_list = new global::System.Collections.Generic.List<AFMsg.PlayerRecordBase>();
    [global::ProtoBuf.ProtoMember(1, Name=@"record_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.PlayerRecordBase> record_list
    {
      get { return _record_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BrocastMsg")]
  public partial class BrocastMsg : global::ProtoBuf.IExtensible
  {
    public BrocastMsg() {}
    
    private AFMsg.Ident _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AFMsg.Ident player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private byte[] _msg_data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] msg_data
    {
      get { return _msg_data; }
      set { _msg_data = value; }
    }
    private long _nMsgID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nMsgID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long nMsgID
    {
      get { return _nMsgID; }
      set { _nMsgID = value; }
    }
    private readonly global::System.Collections.Generic.List<AFMsg.Ident> _player_Client_list = new global::System.Collections.Generic.List<AFMsg.Ident>();
    [global::ProtoBuf.ProtoMember(4, Name=@"player_Client_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AFMsg.Ident> player_Client_list
    {
      get { return _player_Client_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Position")]
  public partial class Position : global::ProtoBuf.IExtensible
  {
    public Position() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCommand")]
  public partial class ReqCommand : global::ProtoBuf.IExtensible
  {
    public ReqCommand() {}
    
    private AFMsg.Ident _control_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"control_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public AFMsg.Ident control_id
    {
      get { return _control_id; }
      set { _control_id = value; }
    }
    private AFMsg.ReqCommand.EGameCommandType _command_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"command_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public AFMsg.ReqCommand.EGameCommandType command_id
    {
      get { return _command_id; }
      set { _command_id = value; }
    }
    private byte[] _command_str_value = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"command_str_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] command_str_value
    {
      get { return _command_str_value; }
      set { _command_str_value = value; }
    }
    private long _command_value_int = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"command_value_int", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long command_value_int
    {
      get { return _command_value_int; }
      set { _command_value_int = value; }
    }
    private float _command_value_float = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"command_value_float", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float command_value_float
    {
      get { return _command_value_float; }
      set { _command_value_float = value; }
    }
    private byte[] _command_value_str = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"command_value_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] command_value_str
    {
      get { return _command_value_str; }
      set { _command_value_str = value; }
    }
    private AFMsg.Ident _command_value_object = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"command_value_object", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public AFMsg.Ident command_value_object
    {
      get { return _command_value_object; }
      set { _command_value_object = value; }
    }
    private int _row = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int row
    {
      get { return _row; }
      set { _row = value; }
    }
    private int _col = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"col", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int col
    {
      get { return _col; }
      set { _col = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"EGameCommandType")]
    public enum EGameCommandType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGCT_MODIY_PROPERTY", Value=0)]
      EGCT_MODIY_PROPERTY = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGCT_MODIY_ITEM", Value=1)]
      EGCT_MODIY_ITEM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGCT_CREATE_OBJECT", Value=2)]
      EGCT_CREATE_OBJECT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGCT_ADD_ROLE_EXP", Value=3)]
      EGCT_ADD_ROLE_EXP = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}