// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AFMsgURl.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "AFMsgURl.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace AFMsg {

namespace {

const ::google::protobuf::Descriptor* PackSURLParam_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PackSURLParam_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_AFMsgURl_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_AFMsgURl_2eproto() {
  protobuf_AddDesc_AFMsgURl_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "AFMsgURl.proto");
  GOOGLE_CHECK(file != NULL);
  PackSURLParam_descriptor_ = file->message_type(0);
  static const int PackSURLParam_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PackSURLParam, strurl_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PackSURLParam, strgetparams_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PackSURLParam, strbodydata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PackSURLParam, strcookies_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PackSURLParam, ftimeoutsec_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PackSURLParam, strrsp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PackSURLParam, nret_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PackSURLParam, nreqid_),
  };
  PackSURLParam_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PackSURLParam_descriptor_,
      PackSURLParam::default_instance_,
      PackSURLParam_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PackSURLParam, _has_bits_[0]),
      -1,
      -1,
      sizeof(PackSURLParam),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PackSURLParam, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_AFMsgURl_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PackSURLParam_descriptor_, &PackSURLParam::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_AFMsgURl_2eproto() {
  delete PackSURLParam::default_instance_;
  delete PackSURLParam_reflection_;
}

void protobuf_AddDesc_AFMsgURl_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_AFMsgURl_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016AFMsgURl.proto\022\005AFMsg\"\241\001\n\rPackSURLPara"
    "m\022\016\n\006strUrl\030\001 \002(\014\022\024\n\014strGetParams\030\002 \002(\014\022"
    "\023\n\013strBodyData\030\003 \002(\014\022\022\n\nstrCookies\030\004 \002(\014"
    "\022\023\n\013fTimeOutSec\030\005 \002(\001\022\016\n\006strRsp\030\006 \002(\014\022\014\n"
    "\004nRet\030\007 \002(\003\022\016\n\006nReqID\030\010 \002(\003", 187);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AFMsgURl.proto", &protobuf_RegisterTypes);
  PackSURLParam::default_instance_ = new PackSURLParam();
  PackSURLParam::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_AFMsgURl_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_AFMsgURl_2eproto {
  StaticDescriptorInitializer_AFMsgURl_2eproto() {
    protobuf_AddDesc_AFMsgURl_2eproto();
  }
} static_descriptor_initializer_AFMsgURl_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PackSURLParam::kStrUrlFieldNumber;
const int PackSURLParam::kStrGetParamsFieldNumber;
const int PackSURLParam::kStrBodyDataFieldNumber;
const int PackSURLParam::kStrCookiesFieldNumber;
const int PackSURLParam::kFTimeOutSecFieldNumber;
const int PackSURLParam::kStrRspFieldNumber;
const int PackSURLParam::kNRetFieldNumber;
const int PackSURLParam::kNReqIDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PackSURLParam::PackSURLParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:AFMsg.PackSURLParam)
}

void PackSURLParam::InitAsDefaultInstance() {
}

PackSURLParam::PackSURLParam(const PackSURLParam& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:AFMsg.PackSURLParam)
}

void PackSURLParam::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  strurl_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strgetparams_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strbodydata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcookies_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ftimeoutsec_ = 0;
  strrsp_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nret_ = GOOGLE_LONGLONG(0);
  nreqid_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PackSURLParam::~PackSURLParam() {
  // @@protoc_insertion_point(destructor:AFMsg.PackSURLParam)
  SharedDtor();
}

void PackSURLParam::SharedDtor() {
  strurl_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strgetparams_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strbodydata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strcookies_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strrsp_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void PackSURLParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PackSURLParam::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PackSURLParam_descriptor_;
}

const PackSURLParam& PackSURLParam::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_AFMsgURl_2eproto();
  return *default_instance_;
}

PackSURLParam* PackSURLParam::default_instance_ = NULL;

PackSURLParam* PackSURLParam::New(::google::protobuf::Arena* arena) const {
  PackSURLParam* n = new PackSURLParam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PackSURLParam::Clear() {
// @@protoc_insertion_point(message_clear_start:AFMsg.PackSURLParam)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PackSURLParam, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PackSURLParam*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 255u) {
    ZR_(nret_, nreqid_);
    if (has_strurl()) {
      strurl_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_strgetparams()) {
      strgetparams_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_strbodydata()) {
      strbodydata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_strcookies()) {
      strcookies_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    ftimeoutsec_ = 0;
    if (has_strrsp()) {
      strrsp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool PackSURLParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AFMsg.PackSURLParam)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes strUrl = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strurl()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_strGetParams;
        break;
      }

      // required bytes strGetParams = 2;
      case 2: {
        if (tag == 18) {
         parse_strGetParams:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strgetparams()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_strBodyData;
        break;
      }

      // required bytes strBodyData = 3;
      case 3: {
        if (tag == 26) {
         parse_strBodyData:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strbodydata()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_strCookies;
        break;
      }

      // required bytes strCookies = 4;
      case 4: {
        if (tag == 34) {
         parse_strCookies:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strcookies()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_fTimeOutSec;
        break;
      }

      // required double fTimeOutSec = 5;
      case 5: {
        if (tag == 41) {
         parse_fTimeOutSec:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &ftimeoutsec_)));
          set_has_ftimeoutsec();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_strRsp;
        break;
      }

      // required bytes strRsp = 6;
      case 6: {
        if (tag == 50) {
         parse_strRsp:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_strrsp()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_nRet;
        break;
      }

      // required int64 nRet = 7;
      case 7: {
        if (tag == 56) {
         parse_nRet:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &nret_)));
          set_has_nret();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_nReqID;
        break;
      }

      // required int64 nReqID = 8;
      case 8: {
        if (tag == 64) {
         parse_nReqID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &nreqid_)));
          set_has_nreqid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AFMsg.PackSURLParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AFMsg.PackSURLParam)
  return false;
#undef DO_
}

void PackSURLParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AFMsg.PackSURLParam)
  // required bytes strUrl = 1;
  if (has_strurl()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->strurl(), output);
  }

  // required bytes strGetParams = 2;
  if (has_strgetparams()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->strgetparams(), output);
  }

  // required bytes strBodyData = 3;
  if (has_strbodydata()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->strbodydata(), output);
  }

  // required bytes strCookies = 4;
  if (has_strcookies()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->strcookies(), output);
  }

  // required double fTimeOutSec = 5;
  if (has_ftimeoutsec()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->ftimeoutsec(), output);
  }

  // required bytes strRsp = 6;
  if (has_strrsp()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      6, this->strrsp(), output);
  }

  // required int64 nRet = 7;
  if (has_nret()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->nret(), output);
  }

  // required int64 nReqID = 8;
  if (has_nreqid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->nreqid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:AFMsg.PackSURLParam)
}

::google::protobuf::uint8* PackSURLParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:AFMsg.PackSURLParam)
  // required bytes strUrl = 1;
  if (has_strurl()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->strurl(), target);
  }

  // required bytes strGetParams = 2;
  if (has_strgetparams()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->strgetparams(), target);
  }

  // required bytes strBodyData = 3;
  if (has_strbodydata()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->strbodydata(), target);
  }

  // required bytes strCookies = 4;
  if (has_strcookies()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->strcookies(), target);
  }

  // required double fTimeOutSec = 5;
  if (has_ftimeoutsec()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->ftimeoutsec(), target);
  }

  // required bytes strRsp = 6;
  if (has_strrsp()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        6, this->strrsp(), target);
  }

  // required int64 nRet = 7;
  if (has_nret()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->nret(), target);
  }

  // required int64 nReqID = 8;
  if (has_nreqid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->nreqid(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AFMsg.PackSURLParam)
  return target;
}

int PackSURLParam::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:AFMsg.PackSURLParam)
  int total_size = 0;

  if (has_strurl()) {
    // required bytes strUrl = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strurl());
  }

  if (has_strgetparams()) {
    // required bytes strGetParams = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strgetparams());
  }

  if (has_strbodydata()) {
    // required bytes strBodyData = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strbodydata());
  }

  if (has_strcookies()) {
    // required bytes strCookies = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strcookies());
  }

  if (has_ftimeoutsec()) {
    // required double fTimeOutSec = 5;
    total_size += 1 + 8;
  }

  if (has_strrsp()) {
    // required bytes strRsp = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strrsp());
  }

  if (has_nret()) {
    // required int64 nRet = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->nret());
  }

  if (has_nreqid()) {
    // required int64 nReqID = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->nreqid());
  }

  return total_size;
}
int PackSURLParam::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:AFMsg.PackSURLParam)
  int total_size = 0;

  if (((_has_bits_[0] & 0x000000ff) ^ 0x000000ff) == 0) {  // All required fields are present.
    // required bytes strUrl = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strurl());

    // required bytes strGetParams = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strgetparams());

    // required bytes strBodyData = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strbodydata());

    // required bytes strCookies = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strcookies());

    // required double fTimeOutSec = 5;
    total_size += 1 + 8;

    // required bytes strRsp = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->strrsp());

    // required int64 nRet = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->nret());

    // required int64 nReqID = 8;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->nreqid());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PackSURLParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:AFMsg.PackSURLParam)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PackSURLParam* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PackSURLParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:AFMsg.PackSURLParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:AFMsg.PackSURLParam)
    MergeFrom(*source);
  }
}

void PackSURLParam::MergeFrom(const PackSURLParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:AFMsg.PackSURLParam)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_strurl()) {
      set_has_strurl();
      strurl_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strurl_);
    }
    if (from.has_strgetparams()) {
      set_has_strgetparams();
      strgetparams_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strgetparams_);
    }
    if (from.has_strbodydata()) {
      set_has_strbodydata();
      strbodydata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strbodydata_);
    }
    if (from.has_strcookies()) {
      set_has_strcookies();
      strcookies_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strcookies_);
    }
    if (from.has_ftimeoutsec()) {
      set_ftimeoutsec(from.ftimeoutsec());
    }
    if (from.has_strrsp()) {
      set_has_strrsp();
      strrsp_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strrsp_);
    }
    if (from.has_nret()) {
      set_nret(from.nret());
    }
    if (from.has_nreqid()) {
      set_nreqid(from.nreqid());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void PackSURLParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:AFMsg.PackSURLParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PackSURLParam::CopyFrom(const PackSURLParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AFMsg.PackSURLParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PackSURLParam::IsInitialized() const {
  if ((_has_bits_[0] & 0x000000ff) != 0x000000ff) return false;

  return true;
}

void PackSURLParam::Swap(PackSURLParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PackSURLParam::InternalSwap(PackSURLParam* other) {
  strurl_.Swap(&other->strurl_);
  strgetparams_.Swap(&other->strgetparams_);
  strbodydata_.Swap(&other->strbodydata_);
  strcookies_.Swap(&other->strcookies_);
  std::swap(ftimeoutsec_, other->ftimeoutsec_);
  strrsp_.Swap(&other->strrsp_);
  std::swap(nret_, other->nret_);
  std::swap(nreqid_, other->nreqid_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PackSURLParam::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PackSURLParam_descriptor_;
  metadata.reflection = PackSURLParam_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PackSURLParam

// required bytes strUrl = 1;
bool PackSURLParam::has_strurl() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void PackSURLParam::set_has_strurl() {
  _has_bits_[0] |= 0x00000001u;
}
void PackSURLParam::clear_has_strurl() {
  _has_bits_[0] &= ~0x00000001u;
}
void PackSURLParam::clear_strurl() {
  strurl_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_strurl();
}
 const ::std::string& PackSURLParam::strurl() const {
  // @@protoc_insertion_point(field_get:AFMsg.PackSURLParam.strUrl)
  return strurl_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PackSURLParam::set_strurl(const ::std::string& value) {
  set_has_strurl();
  strurl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AFMsg.PackSURLParam.strUrl)
}
 void PackSURLParam::set_strurl(const char* value) {
  set_has_strurl();
  strurl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AFMsg.PackSURLParam.strUrl)
}
 void PackSURLParam::set_strurl(const void* value, size_t size) {
  set_has_strurl();
  strurl_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AFMsg.PackSURLParam.strUrl)
}
 ::std::string* PackSURLParam::mutable_strurl() {
  set_has_strurl();
  // @@protoc_insertion_point(field_mutable:AFMsg.PackSURLParam.strUrl)
  return strurl_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PackSURLParam::release_strurl() {
  // @@protoc_insertion_point(field_release:AFMsg.PackSURLParam.strUrl)
  clear_has_strurl();
  return strurl_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PackSURLParam::set_allocated_strurl(::std::string* strurl) {
  if (strurl != NULL) {
    set_has_strurl();
  } else {
    clear_has_strurl();
  }
  strurl_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strurl);
  // @@protoc_insertion_point(field_set_allocated:AFMsg.PackSURLParam.strUrl)
}

// required bytes strGetParams = 2;
bool PackSURLParam::has_strgetparams() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void PackSURLParam::set_has_strgetparams() {
  _has_bits_[0] |= 0x00000002u;
}
void PackSURLParam::clear_has_strgetparams() {
  _has_bits_[0] &= ~0x00000002u;
}
void PackSURLParam::clear_strgetparams() {
  strgetparams_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_strgetparams();
}
 const ::std::string& PackSURLParam::strgetparams() const {
  // @@protoc_insertion_point(field_get:AFMsg.PackSURLParam.strGetParams)
  return strgetparams_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PackSURLParam::set_strgetparams(const ::std::string& value) {
  set_has_strgetparams();
  strgetparams_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AFMsg.PackSURLParam.strGetParams)
}
 void PackSURLParam::set_strgetparams(const char* value) {
  set_has_strgetparams();
  strgetparams_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AFMsg.PackSURLParam.strGetParams)
}
 void PackSURLParam::set_strgetparams(const void* value, size_t size) {
  set_has_strgetparams();
  strgetparams_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AFMsg.PackSURLParam.strGetParams)
}
 ::std::string* PackSURLParam::mutable_strgetparams() {
  set_has_strgetparams();
  // @@protoc_insertion_point(field_mutable:AFMsg.PackSURLParam.strGetParams)
  return strgetparams_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PackSURLParam::release_strgetparams() {
  // @@protoc_insertion_point(field_release:AFMsg.PackSURLParam.strGetParams)
  clear_has_strgetparams();
  return strgetparams_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PackSURLParam::set_allocated_strgetparams(::std::string* strgetparams) {
  if (strgetparams != NULL) {
    set_has_strgetparams();
  } else {
    clear_has_strgetparams();
  }
  strgetparams_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strgetparams);
  // @@protoc_insertion_point(field_set_allocated:AFMsg.PackSURLParam.strGetParams)
}

// required bytes strBodyData = 3;
bool PackSURLParam::has_strbodydata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void PackSURLParam::set_has_strbodydata() {
  _has_bits_[0] |= 0x00000004u;
}
void PackSURLParam::clear_has_strbodydata() {
  _has_bits_[0] &= ~0x00000004u;
}
void PackSURLParam::clear_strbodydata() {
  strbodydata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_strbodydata();
}
 const ::std::string& PackSURLParam::strbodydata() const {
  // @@protoc_insertion_point(field_get:AFMsg.PackSURLParam.strBodyData)
  return strbodydata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PackSURLParam::set_strbodydata(const ::std::string& value) {
  set_has_strbodydata();
  strbodydata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AFMsg.PackSURLParam.strBodyData)
}
 void PackSURLParam::set_strbodydata(const char* value) {
  set_has_strbodydata();
  strbodydata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AFMsg.PackSURLParam.strBodyData)
}
 void PackSURLParam::set_strbodydata(const void* value, size_t size) {
  set_has_strbodydata();
  strbodydata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AFMsg.PackSURLParam.strBodyData)
}
 ::std::string* PackSURLParam::mutable_strbodydata() {
  set_has_strbodydata();
  // @@protoc_insertion_point(field_mutable:AFMsg.PackSURLParam.strBodyData)
  return strbodydata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PackSURLParam::release_strbodydata() {
  // @@protoc_insertion_point(field_release:AFMsg.PackSURLParam.strBodyData)
  clear_has_strbodydata();
  return strbodydata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PackSURLParam::set_allocated_strbodydata(::std::string* strbodydata) {
  if (strbodydata != NULL) {
    set_has_strbodydata();
  } else {
    clear_has_strbodydata();
  }
  strbodydata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strbodydata);
  // @@protoc_insertion_point(field_set_allocated:AFMsg.PackSURLParam.strBodyData)
}

// required bytes strCookies = 4;
bool PackSURLParam::has_strcookies() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void PackSURLParam::set_has_strcookies() {
  _has_bits_[0] |= 0x00000008u;
}
void PackSURLParam::clear_has_strcookies() {
  _has_bits_[0] &= ~0x00000008u;
}
void PackSURLParam::clear_strcookies() {
  strcookies_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_strcookies();
}
 const ::std::string& PackSURLParam::strcookies() const {
  // @@protoc_insertion_point(field_get:AFMsg.PackSURLParam.strCookies)
  return strcookies_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PackSURLParam::set_strcookies(const ::std::string& value) {
  set_has_strcookies();
  strcookies_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AFMsg.PackSURLParam.strCookies)
}
 void PackSURLParam::set_strcookies(const char* value) {
  set_has_strcookies();
  strcookies_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AFMsg.PackSURLParam.strCookies)
}
 void PackSURLParam::set_strcookies(const void* value, size_t size) {
  set_has_strcookies();
  strcookies_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AFMsg.PackSURLParam.strCookies)
}
 ::std::string* PackSURLParam::mutable_strcookies() {
  set_has_strcookies();
  // @@protoc_insertion_point(field_mutable:AFMsg.PackSURLParam.strCookies)
  return strcookies_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PackSURLParam::release_strcookies() {
  // @@protoc_insertion_point(field_release:AFMsg.PackSURLParam.strCookies)
  clear_has_strcookies();
  return strcookies_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PackSURLParam::set_allocated_strcookies(::std::string* strcookies) {
  if (strcookies != NULL) {
    set_has_strcookies();
  } else {
    clear_has_strcookies();
  }
  strcookies_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strcookies);
  // @@protoc_insertion_point(field_set_allocated:AFMsg.PackSURLParam.strCookies)
}

// required double fTimeOutSec = 5;
bool PackSURLParam::has_ftimeoutsec() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void PackSURLParam::set_has_ftimeoutsec() {
  _has_bits_[0] |= 0x00000010u;
}
void PackSURLParam::clear_has_ftimeoutsec() {
  _has_bits_[0] &= ~0x00000010u;
}
void PackSURLParam::clear_ftimeoutsec() {
  ftimeoutsec_ = 0;
  clear_has_ftimeoutsec();
}
 double PackSURLParam::ftimeoutsec() const {
  // @@protoc_insertion_point(field_get:AFMsg.PackSURLParam.fTimeOutSec)
  return ftimeoutsec_;
}
 void PackSURLParam::set_ftimeoutsec(double value) {
  set_has_ftimeoutsec();
  ftimeoutsec_ = value;
  // @@protoc_insertion_point(field_set:AFMsg.PackSURLParam.fTimeOutSec)
}

// required bytes strRsp = 6;
bool PackSURLParam::has_strrsp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void PackSURLParam::set_has_strrsp() {
  _has_bits_[0] |= 0x00000020u;
}
void PackSURLParam::clear_has_strrsp() {
  _has_bits_[0] &= ~0x00000020u;
}
void PackSURLParam::clear_strrsp() {
  strrsp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_strrsp();
}
 const ::std::string& PackSURLParam::strrsp() const {
  // @@protoc_insertion_point(field_get:AFMsg.PackSURLParam.strRsp)
  return strrsp_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PackSURLParam::set_strrsp(const ::std::string& value) {
  set_has_strrsp();
  strrsp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:AFMsg.PackSURLParam.strRsp)
}
 void PackSURLParam::set_strrsp(const char* value) {
  set_has_strrsp();
  strrsp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:AFMsg.PackSURLParam.strRsp)
}
 void PackSURLParam::set_strrsp(const void* value, size_t size) {
  set_has_strrsp();
  strrsp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:AFMsg.PackSURLParam.strRsp)
}
 ::std::string* PackSURLParam::mutable_strrsp() {
  set_has_strrsp();
  // @@protoc_insertion_point(field_mutable:AFMsg.PackSURLParam.strRsp)
  return strrsp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PackSURLParam::release_strrsp() {
  // @@protoc_insertion_point(field_release:AFMsg.PackSURLParam.strRsp)
  clear_has_strrsp();
  return strrsp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PackSURLParam::set_allocated_strrsp(::std::string* strrsp) {
  if (strrsp != NULL) {
    set_has_strrsp();
  } else {
    clear_has_strrsp();
  }
  strrsp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strrsp);
  // @@protoc_insertion_point(field_set_allocated:AFMsg.PackSURLParam.strRsp)
}

// required int64 nRet = 7;
bool PackSURLParam::has_nret() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void PackSURLParam::set_has_nret() {
  _has_bits_[0] |= 0x00000040u;
}
void PackSURLParam::clear_has_nret() {
  _has_bits_[0] &= ~0x00000040u;
}
void PackSURLParam::clear_nret() {
  nret_ = GOOGLE_LONGLONG(0);
  clear_has_nret();
}
 ::google::protobuf::int64 PackSURLParam::nret() const {
  // @@protoc_insertion_point(field_get:AFMsg.PackSURLParam.nRet)
  return nret_;
}
 void PackSURLParam::set_nret(::google::protobuf::int64 value) {
  set_has_nret();
  nret_ = value;
  // @@protoc_insertion_point(field_set:AFMsg.PackSURLParam.nRet)
}

// required int64 nReqID = 8;
bool PackSURLParam::has_nreqid() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void PackSURLParam::set_has_nreqid() {
  _has_bits_[0] |= 0x00000080u;
}
void PackSURLParam::clear_has_nreqid() {
  _has_bits_[0] &= ~0x00000080u;
}
void PackSURLParam::clear_nreqid() {
  nreqid_ = GOOGLE_LONGLONG(0);
  clear_has_nreqid();
}
 ::google::protobuf::int64 PackSURLParam::nreqid() const {
  // @@protoc_insertion_point(field_get:AFMsg.PackSURLParam.nReqID)
  return nreqid_;
}
 void PackSURLParam::set_nreqid(::google::protobuf::int64 value) {
  set_has_nreqid();
  nreqid_ = value;
  // @@protoc_insertion_point(field_set:AFMsg.PackSURLParam.nReqID)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace AFMsg

// @@protoc_insertion_point(global_scope)
