// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AFMsgMysql.proto

#include "AFMsgMysql.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace AFMsg {
class PackMysqlParamDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PackMysqlParam>
      _instance;
} _PackMysqlParam_default_instance_;
class PackMysqlServerInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PackMysqlServerInfo>
      _instance;
} _PackMysqlServerInfo_default_instance_;
}  // namespace AFMsg
namespace protobuf_AFMsgMysql_2eproto {
void InitDefaultsPackMysqlParamImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::AFMsg::_PackMysqlParam_default_instance_;
    new (ptr) ::AFMsg::PackMysqlParam();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::AFMsg::PackMysqlParam::InitAsDefaultInstance();
}

void InitDefaultsPackMysqlParam() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPackMysqlParamImpl);
}

void InitDefaultsPackMysqlServerInfoImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::AFMsg::_PackMysqlServerInfo_default_instance_;
    new (ptr) ::AFMsg::PackMysqlServerInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::AFMsg::PackMysqlServerInfo::InitAsDefaultInstance();
}

void InitDefaultsPackMysqlServerInfo() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPackMysqlServerInfoImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlParam, strrecordname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlParam, strkey_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlParam, fieldveclist_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlParam, valueveclist_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlParam, bexit_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlParam, nreqid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlParam, nret_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlParam, etype_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlServerInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlServerInfo, nrconnecttime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlServerInfo, nrconnecount_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlServerInfo, nport_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlServerInfo, strdbname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlServerInfo, strdnsip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlServerInfo, strdbuser_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlServerInfo, strdbpwd_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::AFMsg::PackMysqlServerInfo, nserverid_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::AFMsg::PackMysqlParam)},
  { 13, -1, sizeof(::AFMsg::PackMysqlServerInfo)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::AFMsg::_PackMysqlParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::AFMsg::_PackMysqlServerInfo_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "AFMsgMysql.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020AFMsgMysql.proto\022\005AFMsg\"\237\001\n\016PackMysqlP"
      "aram\022\025\n\rstrRecordName\030\001 \001(\t\022\016\n\006strKey\030\002 "
      "\001(\t\022\024\n\014fieldVecList\030\003 \001(\t\022\024\n\014valueVecLis"
      "t\030\004 \001(\t\022\r\n\005bExit\030\005 \001(\003\022\016\n\006nreqid\030\006 \001(\003\022\014"
      "\n\004nRet\030\007 \001(\003\022\r\n\005eType\030\010 \001(\003\"\256\001\n\023PackMysq"
      "lServerInfo\022\025\n\rnRconnectTime\030\001 \001(\003\022\024\n\014nR"
      "conneCount\030\002 \001(\003\022\r\n\005nPort\030\003 \001(\003\022\021\n\tstrDB"
      "Name\030\004 \001(\t\022\020\n\010strDnsIp\030\005 \001(\t\022\021\n\tstrDBUse"
      "r\030\006 \001(\t\022\020\n\010strDBPwd\030\007 \001(\t\022\021\n\tnServerID\030\010"
      " \001(\003b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 372);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AFMsgMysql.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_AFMsgMysql_2eproto
namespace AFMsg {

// ===================================================================

void PackMysqlParam::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PackMysqlParam::kStrRecordNameFieldNumber;
const int PackMysqlParam::kStrKeyFieldNumber;
const int PackMysqlParam::kFieldVecListFieldNumber;
const int PackMysqlParam::kValueVecListFieldNumber;
const int PackMysqlParam::kBExitFieldNumber;
const int PackMysqlParam::kNreqidFieldNumber;
const int PackMysqlParam::kNRetFieldNumber;
const int PackMysqlParam::kETypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PackMysqlParam::PackMysqlParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_AFMsgMysql_2eproto::InitDefaultsPackMysqlParam();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:AFMsg.PackMysqlParam)
}
PackMysqlParam::PackMysqlParam(const PackMysqlParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  strrecordname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.strrecordname().size() > 0) {
    strrecordname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strrecordname_);
  }
  strkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.strkey().size() > 0) {
    strkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strkey_);
  }
  fieldveclist_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.fieldveclist().size() > 0) {
    fieldveclist_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fieldveclist_);
  }
  valueveclist_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.valueveclist().size() > 0) {
    valueveclist_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.valueveclist_);
  }
  ::memcpy(&bexit_, &from.bexit_,
    static_cast<size_t>(reinterpret_cast<char*>(&etype_) -
    reinterpret_cast<char*>(&bexit_)) + sizeof(etype_));
  // @@protoc_insertion_point(copy_constructor:AFMsg.PackMysqlParam)
}

void PackMysqlParam::SharedCtor() {
  strrecordname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fieldveclist_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valueveclist_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&bexit_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&etype_) -
      reinterpret_cast<char*>(&bexit_)) + sizeof(etype_));
  _cached_size_ = 0;
}

PackMysqlParam::~PackMysqlParam() {
  // @@protoc_insertion_point(destructor:AFMsg.PackMysqlParam)
  SharedDtor();
}

void PackMysqlParam::SharedDtor() {
  strrecordname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strkey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fieldveclist_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valueveclist_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PackMysqlParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PackMysqlParam::descriptor() {
  ::protobuf_AFMsgMysql_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_AFMsgMysql_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PackMysqlParam& PackMysqlParam::default_instance() {
  ::protobuf_AFMsgMysql_2eproto::InitDefaultsPackMysqlParam();
  return *internal_default_instance();
}

PackMysqlParam* PackMysqlParam::New(::google::protobuf::Arena* arena) const {
  PackMysqlParam* n = new PackMysqlParam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PackMysqlParam::Clear() {
// @@protoc_insertion_point(message_clear_start:AFMsg.PackMysqlParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  strrecordname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fieldveclist_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valueveclist_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&bexit_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&etype_) -
      reinterpret_cast<char*>(&bexit_)) + sizeof(etype_));
  _internal_metadata_.Clear();
}

bool PackMysqlParam::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AFMsg.PackMysqlParam)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string strRecordName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strrecordname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->strrecordname().data(), static_cast<int>(this->strrecordname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "AFMsg.PackMysqlParam.strRecordName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string strKey = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strkey()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->strkey().data(), static_cast<int>(this->strkey().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "AFMsg.PackMysqlParam.strKey"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string fieldVecList = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fieldveclist()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fieldveclist().data(), static_cast<int>(this->fieldveclist().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "AFMsg.PackMysqlParam.fieldVecList"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string valueVecList = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_valueveclist()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->valueveclist().data(), static_cast<int>(this->valueveclist().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "AFMsg.PackMysqlParam.valueVecList"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 bExit = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &bexit_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 nreqid = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &nreqid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 nRet = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &nret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 eType = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &etype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AFMsg.PackMysqlParam)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AFMsg.PackMysqlParam)
  return false;
#undef DO_
}

void PackMysqlParam::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AFMsg.PackMysqlParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string strRecordName = 1;
  if (this->strrecordname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strrecordname().data(), static_cast<int>(this->strrecordname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlParam.strRecordName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->strrecordname(), output);
  }

  // string strKey = 2;
  if (this->strkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strkey().data(), static_cast<int>(this->strkey().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlParam.strKey");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->strkey(), output);
  }

  // string fieldVecList = 3;
  if (this->fieldveclist().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fieldveclist().data(), static_cast<int>(this->fieldveclist().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlParam.fieldVecList");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->fieldveclist(), output);
  }

  // string valueVecList = 4;
  if (this->valueveclist().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->valueveclist().data(), static_cast<int>(this->valueveclist().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlParam.valueVecList");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->valueveclist(), output);
  }

  // int64 bExit = 5;
  if (this->bexit() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->bexit(), output);
  }

  // int64 nreqid = 6;
  if (this->nreqid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(6, this->nreqid(), output);
  }

  // int64 nRet = 7;
  if (this->nret() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->nret(), output);
  }

  // int64 eType = 8;
  if (this->etype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->etype(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:AFMsg.PackMysqlParam)
}

::google::protobuf::uint8* PackMysqlParam::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:AFMsg.PackMysqlParam)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string strRecordName = 1;
  if (this->strrecordname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strrecordname().data(), static_cast<int>(this->strrecordname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlParam.strRecordName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->strrecordname(), target);
  }

  // string strKey = 2;
  if (this->strkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strkey().data(), static_cast<int>(this->strkey().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlParam.strKey");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->strkey(), target);
  }

  // string fieldVecList = 3;
  if (this->fieldveclist().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fieldveclist().data(), static_cast<int>(this->fieldveclist().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlParam.fieldVecList");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->fieldveclist(), target);
  }

  // string valueVecList = 4;
  if (this->valueveclist().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->valueveclist().data(), static_cast<int>(this->valueveclist().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlParam.valueVecList");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->valueveclist(), target);
  }

  // int64 bExit = 5;
  if (this->bexit() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->bexit(), target);
  }

  // int64 nreqid = 6;
  if (this->nreqid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(6, this->nreqid(), target);
  }

  // int64 nRet = 7;
  if (this->nret() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->nret(), target);
  }

  // int64 eType = 8;
  if (this->etype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->etype(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AFMsg.PackMysqlParam)
  return target;
}

size_t PackMysqlParam::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AFMsg.PackMysqlParam)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string strRecordName = 1;
  if (this->strrecordname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->strrecordname());
  }

  // string strKey = 2;
  if (this->strkey().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->strkey());
  }

  // string fieldVecList = 3;
  if (this->fieldveclist().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fieldveclist());
  }

  // string valueVecList = 4;
  if (this->valueveclist().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->valueveclist());
  }

  // int64 bExit = 5;
  if (this->bexit() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->bexit());
  }

  // int64 nreqid = 6;
  if (this->nreqid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->nreqid());
  }

  // int64 nRet = 7;
  if (this->nret() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->nret());
  }

  // int64 eType = 8;
  if (this->etype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->etype());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PackMysqlParam::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:AFMsg.PackMysqlParam)
  GOOGLE_DCHECK_NE(&from, this);
  const PackMysqlParam* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PackMysqlParam>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:AFMsg.PackMysqlParam)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:AFMsg.PackMysqlParam)
    MergeFrom(*source);
  }
}

void PackMysqlParam::MergeFrom(const PackMysqlParam& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:AFMsg.PackMysqlParam)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.strrecordname().size() > 0) {

    strrecordname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strrecordname_);
  }
  if (from.strkey().size() > 0) {

    strkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strkey_);
  }
  if (from.fieldveclist().size() > 0) {

    fieldveclist_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fieldveclist_);
  }
  if (from.valueveclist().size() > 0) {

    valueveclist_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.valueveclist_);
  }
  if (from.bexit() != 0) {
    set_bexit(from.bexit());
  }
  if (from.nreqid() != 0) {
    set_nreqid(from.nreqid());
  }
  if (from.nret() != 0) {
    set_nret(from.nret());
  }
  if (from.etype() != 0) {
    set_etype(from.etype());
  }
}

void PackMysqlParam::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:AFMsg.PackMysqlParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PackMysqlParam::CopyFrom(const PackMysqlParam& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AFMsg.PackMysqlParam)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PackMysqlParam::IsInitialized() const {
  return true;
}

void PackMysqlParam::Swap(PackMysqlParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PackMysqlParam::InternalSwap(PackMysqlParam* other) {
  using std::swap;
  strrecordname_.Swap(&other->strrecordname_);
  strkey_.Swap(&other->strkey_);
  fieldveclist_.Swap(&other->fieldveclist_);
  valueveclist_.Swap(&other->valueveclist_);
  swap(bexit_, other->bexit_);
  swap(nreqid_, other->nreqid_);
  swap(nret_, other->nret_);
  swap(etype_, other->etype_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PackMysqlParam::GetMetadata() const {
  protobuf_AFMsgMysql_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_AFMsgMysql_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PackMysqlServerInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PackMysqlServerInfo::kNRconnectTimeFieldNumber;
const int PackMysqlServerInfo::kNRconneCountFieldNumber;
const int PackMysqlServerInfo::kNPortFieldNumber;
const int PackMysqlServerInfo::kStrDBNameFieldNumber;
const int PackMysqlServerInfo::kStrDnsIpFieldNumber;
const int PackMysqlServerInfo::kStrDBUserFieldNumber;
const int PackMysqlServerInfo::kStrDBPwdFieldNumber;
const int PackMysqlServerInfo::kNServerIDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PackMysqlServerInfo::PackMysqlServerInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_AFMsgMysql_2eproto::InitDefaultsPackMysqlServerInfo();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:AFMsg.PackMysqlServerInfo)
}
PackMysqlServerInfo::PackMysqlServerInfo(const PackMysqlServerInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  strdbname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.strdbname().size() > 0) {
    strdbname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strdbname_);
  }
  strdnsip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.strdnsip().size() > 0) {
    strdnsip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strdnsip_);
  }
  strdbuser_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.strdbuser().size() > 0) {
    strdbuser_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strdbuser_);
  }
  strdbpwd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.strdbpwd().size() > 0) {
    strdbpwd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strdbpwd_);
  }
  ::memcpy(&nrconnecttime_, &from.nrconnecttime_,
    static_cast<size_t>(reinterpret_cast<char*>(&nserverid_) -
    reinterpret_cast<char*>(&nrconnecttime_)) + sizeof(nserverid_));
  // @@protoc_insertion_point(copy_constructor:AFMsg.PackMysqlServerInfo)
}

void PackMysqlServerInfo::SharedCtor() {
  strdbname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdnsip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdbuser_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdbpwd_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&nrconnecttime_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nserverid_) -
      reinterpret_cast<char*>(&nrconnecttime_)) + sizeof(nserverid_));
  _cached_size_ = 0;
}

PackMysqlServerInfo::~PackMysqlServerInfo() {
  // @@protoc_insertion_point(destructor:AFMsg.PackMysqlServerInfo)
  SharedDtor();
}

void PackMysqlServerInfo::SharedDtor() {
  strdbname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdnsip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdbuser_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdbpwd_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PackMysqlServerInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PackMysqlServerInfo::descriptor() {
  ::protobuf_AFMsgMysql_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_AFMsgMysql_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PackMysqlServerInfo& PackMysqlServerInfo::default_instance() {
  ::protobuf_AFMsgMysql_2eproto::InitDefaultsPackMysqlServerInfo();
  return *internal_default_instance();
}

PackMysqlServerInfo* PackMysqlServerInfo::New(::google::protobuf::Arena* arena) const {
  PackMysqlServerInfo* n = new PackMysqlServerInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PackMysqlServerInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:AFMsg.PackMysqlServerInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  strdbname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdnsip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdbuser_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  strdbpwd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&nrconnecttime_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nserverid_) -
      reinterpret_cast<char*>(&nrconnecttime_)) + sizeof(nserverid_));
  _internal_metadata_.Clear();
}

bool PackMysqlServerInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AFMsg.PackMysqlServerInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 nRconnectTime = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &nrconnecttime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 nRconneCount = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &nrconnecount_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 nPort = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &nport_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string strDBName = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strdbname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->strdbname().data(), static_cast<int>(this->strdbname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "AFMsg.PackMysqlServerInfo.strDBName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string strDnsIp = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strdnsip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->strdnsip().data(), static_cast<int>(this->strdnsip().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "AFMsg.PackMysqlServerInfo.strDnsIp"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string strDBUser = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strdbuser()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->strdbuser().data(), static_cast<int>(this->strdbuser().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "AFMsg.PackMysqlServerInfo.strDBUser"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string strDBPwd = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strdbpwd()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->strdbpwd().data(), static_cast<int>(this->strdbpwd().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "AFMsg.PackMysqlServerInfo.strDBPwd"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 nServerID = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &nserverid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AFMsg.PackMysqlServerInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AFMsg.PackMysqlServerInfo)
  return false;
#undef DO_
}

void PackMysqlServerInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AFMsg.PackMysqlServerInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 nRconnectTime = 1;
  if (this->nrconnecttime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->nrconnecttime(), output);
  }

  // int64 nRconneCount = 2;
  if (this->nrconnecount() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->nrconnecount(), output);
  }

  // int64 nPort = 3;
  if (this->nport() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->nport(), output);
  }

  // string strDBName = 4;
  if (this->strdbname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strdbname().data(), static_cast<int>(this->strdbname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlServerInfo.strDBName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->strdbname(), output);
  }

  // string strDnsIp = 5;
  if (this->strdnsip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strdnsip().data(), static_cast<int>(this->strdnsip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlServerInfo.strDnsIp");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->strdnsip(), output);
  }

  // string strDBUser = 6;
  if (this->strdbuser().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strdbuser().data(), static_cast<int>(this->strdbuser().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlServerInfo.strDBUser");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->strdbuser(), output);
  }

  // string strDBPwd = 7;
  if (this->strdbpwd().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strdbpwd().data(), static_cast<int>(this->strdbpwd().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlServerInfo.strDBPwd");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->strdbpwd(), output);
  }

  // int64 nServerID = 8;
  if (this->nserverid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->nserverid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:AFMsg.PackMysqlServerInfo)
}

::google::protobuf::uint8* PackMysqlServerInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:AFMsg.PackMysqlServerInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 nRconnectTime = 1;
  if (this->nrconnecttime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->nrconnecttime(), target);
  }

  // int64 nRconneCount = 2;
  if (this->nrconnecount() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->nrconnecount(), target);
  }

  // int64 nPort = 3;
  if (this->nport() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->nport(), target);
  }

  // string strDBName = 4;
  if (this->strdbname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strdbname().data(), static_cast<int>(this->strdbname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlServerInfo.strDBName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->strdbname(), target);
  }

  // string strDnsIp = 5;
  if (this->strdnsip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strdnsip().data(), static_cast<int>(this->strdnsip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlServerInfo.strDnsIp");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->strdnsip(), target);
  }

  // string strDBUser = 6;
  if (this->strdbuser().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strdbuser().data(), static_cast<int>(this->strdbuser().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlServerInfo.strDBUser");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->strdbuser(), target);
  }

  // string strDBPwd = 7;
  if (this->strdbpwd().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->strdbpwd().data(), static_cast<int>(this->strdbpwd().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "AFMsg.PackMysqlServerInfo.strDBPwd");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->strdbpwd(), target);
  }

  // int64 nServerID = 8;
  if (this->nserverid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->nserverid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AFMsg.PackMysqlServerInfo)
  return target;
}

size_t PackMysqlServerInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:AFMsg.PackMysqlServerInfo)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string strDBName = 4;
  if (this->strdbname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->strdbname());
  }

  // string strDnsIp = 5;
  if (this->strdnsip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->strdnsip());
  }

  // string strDBUser = 6;
  if (this->strdbuser().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->strdbuser());
  }

  // string strDBPwd = 7;
  if (this->strdbpwd().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->strdbpwd());
  }

  // int64 nRconnectTime = 1;
  if (this->nrconnecttime() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->nrconnecttime());
  }

  // int64 nRconneCount = 2;
  if (this->nrconnecount() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->nrconnecount());
  }

  // int64 nPort = 3;
  if (this->nport() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->nport());
  }

  // int64 nServerID = 8;
  if (this->nserverid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->nserverid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PackMysqlServerInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:AFMsg.PackMysqlServerInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const PackMysqlServerInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PackMysqlServerInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:AFMsg.PackMysqlServerInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:AFMsg.PackMysqlServerInfo)
    MergeFrom(*source);
  }
}

void PackMysqlServerInfo::MergeFrom(const PackMysqlServerInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:AFMsg.PackMysqlServerInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.strdbname().size() > 0) {

    strdbname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strdbname_);
  }
  if (from.strdnsip().size() > 0) {

    strdnsip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strdnsip_);
  }
  if (from.strdbuser().size() > 0) {

    strdbuser_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strdbuser_);
  }
  if (from.strdbpwd().size() > 0) {

    strdbpwd_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.strdbpwd_);
  }
  if (from.nrconnecttime() != 0) {
    set_nrconnecttime(from.nrconnecttime());
  }
  if (from.nrconnecount() != 0) {
    set_nrconnecount(from.nrconnecount());
  }
  if (from.nport() != 0) {
    set_nport(from.nport());
  }
  if (from.nserverid() != 0) {
    set_nserverid(from.nserverid());
  }
}

void PackMysqlServerInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:AFMsg.PackMysqlServerInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PackMysqlServerInfo::CopyFrom(const PackMysqlServerInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AFMsg.PackMysqlServerInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PackMysqlServerInfo::IsInitialized() const {
  return true;
}

void PackMysqlServerInfo::Swap(PackMysqlServerInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PackMysqlServerInfo::InternalSwap(PackMysqlServerInfo* other) {
  using std::swap;
  strdbname_.Swap(&other->strdbname_);
  strdnsip_.Swap(&other->strdnsip_);
  strdbuser_.Swap(&other->strdbuser_);
  strdbpwd_.Swap(&other->strdbpwd_);
  swap(nrconnecttime_, other->nrconnecttime_);
  swap(nrconnecount_, other->nrconnecount_);
  swap(nport_, other->nport_);
  swap(nserverid_, other->nserverid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PackMysqlServerInfo::GetMetadata() const {
  protobuf_AFMsgMysql_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_AFMsgMysql_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace AFMsg

// @@protoc_insertion_point(global_scope)
